const $=s=>document.querySelector(s);
const escapeHTML=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const KEY='maklef-21-demo-v1';
const icons={move:'<path d="m3 16 4-4 4 3 4-8 6 3M7 12l-3-2m7 5-3 6m7-14 1-4"/><circle cx="17" cy="3" r="1.5"/>',water:'<path d="M12 3S5 11 5 15a7 7 0 0 0 14 0c0-4-7-12-7-12Z"/><path d="M9 15a3 3 0 0 0 3 3"/>',read:'<path d="M12 6c-3-3-7-3-9-2v15c3-1 6-1 9 1 3-2 6-2 9-1V4c-2-1-6-1-9 2Zm0 0v14"/>',write:'<path d="m4 16 12-12 4 4L8 20H4v-4Zm9-9 4 4M4 22h16"/>',sleep:'<path d="M20 15A9 9 0 0 1 9 4a9 9 0 1 0 11 11Z"/>',custom:'<path d="m12 3 2.7 5.5 6.1.9-4.4 4.3 1 6.1L12 17l-5.4 2.8 1-6.1-4.4-4.3 6.1-.9Z"/>'};
const icon=id=>`<span class="icon" aria-hidden="true"><svg viewBox="0 0 24 24">${icons[id]||icons.custom}</svg></span>`;
const catalog=[{id:'move',title:'תנועה',hint:'הליכה, ריצה או אימון',target:'30 דקות תנועה',time:'18:00'},{id:'water',title:'שתייה',hint:'לתת לזה מקום במהלך היום',target:'לעקוב אחרי השתייה שלי',time:'12:00'},{id:'read',title:'קריאה',hint:'כמה עמודים בשבילי',target:'10 דקות קריאה',time:'21:30'},{id:'write',title:'כתיבה',hint:'רגע לעצור ולהוציא מחשבות',target:'לכתוב כמה שורות',time:'21:00'},{id:'sleep',title:'שגרת ערב',hint:'להוריד הילוך לפני השינה',target:'להניח את הטלפון ב־22:00',time:'22:00'}];
const fresh=()=>({name:'',goal:'',height:'',weight:'',selected:['move','read'],habits:catalog.map(h=>({...h,reminder:false})),start:null,records:{}});
let model=fresh(),storageWorks=true;
try{const saved=JSON.parse(localStorage.getItem(KEY)||'null');if(saved&&Array.isArray(saved.habits)&&Array.isArray(saved.selected)&&saved.records)model=saved;}catch{storageWorks=false;}
let page=model.start?'today':'welcome',demoDay=0,demoRecords={},viewDay=null,previousPage=page;
const calendarDate=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
function dateNumber(date){const [y,m,d]=date.split('-').map(Number);return Date.UTC(y,m-1,d)/86400000;}
function realDay(){return model.start?Math.max(1,Math.min(21,Math.floor(dateNumber(calendarDate())-dateNumber(model.start))+1)):1;}
const currentDay=()=>demoDay||realDay();
const shownDay=()=>viewDay||currentDay();
const records=()=>demoDay?demoRecords:model.records;
const active=()=>model.habits.filter(h=>model.selected.includes(h.id));
const record=(day=shownDay())=>records()[day]||{checks:[],mood:null,note:'',closed:false};
function save(){try{localStorage.setItem(KEY,JSON.stringify(model));storageWorks=true;}catch{storageWorks=false;}}
function updateRecord(change){const d=shownDay();records()[d]={...record(d),...change};if(!demoDay)save();}
const countDone=day=>active().filter(h=>record(day).checks.includes(h.id)).length;
const stats=()=>({checks:Object.values(records()).reduce((n,r)=>n+active().filter(h=>r.checks.includes(h.id)).length,0),days:Object.values(records()).filter(r=>active().some(h=>r.checks.includes(h.id))).length,closed:Object.values(records()).filter(r=>r.closed).length});
const screens=[['welcome','התחלה קטנה','21 יום.<br>בקצב שלך.','מסגרת פשוטה להרגלים שבוחרים עם איתי.'],['goal','מטרה אישית','מה רוצים להרגיש<br>בסוף הדרך?','מטרה במילים שלך, בלי שאלון ארוך.'],['habits','ההרגלים שלי','לא חייבים חמישה.<br>אפשר להתחיל מאחד.','בוחרים הרגלים שמתאימים לאדם, לא להפך.'],['rhythm','הקצב שלי','משהו קטן.<br>בזמן שמתאים לך.','לכל הרגל יעד ברור ושעה לבחירתך.'],['today','היום שלי','פחות לחשוב.<br>יותר פשוט לעשות.','כמה דברים קטנים. סימון אחד לכל דבר שעשית.'],['journey','21 הדלתות','כל יום נפתחת<br>עוד דלת.','רואים את הדרך שעברת ואת מה שעוד לפניך.'],['reflection','סגירת יום','רגע לעצור.<br>ולהקשיב לעצמך.','משוב קצר במקום עוד טופס.'],['summary','ממשיכים מכאן','21 יום הם התחלה.<br>מה לוקחים הלאה?','סיכום אישי ואפשרות להמשיך לליווי עם איתי.'],['contact','בקשר עם איתי','לא צריך לעשות<br>הכול לבד.','אפשר לפתוח שיחה עם סיכום אישי, ולשלוח כשמוכנים.']];
const screen=$('#screen');
const primary=(label,action)=>`<button class="primary" type="button" data-action="${action}">${label}<span aria-hidden="true">←</span></button>`;
const secondary=(label,action)=>`<button class="secondary" type="button" data-action="${action}">${label}</button>`;
const heading=(text,eyebrow='')=>`${eyebrow?`<div class="eyebrow">${eyebrow}</div>`:''}<h2 tabindex="-1">${text}</h2>`;
const actions=(...content)=>`<div class="actions">${content.join('')}</div>`;
const setupStep=n=>`<div class="step"><button class="back" data-go="${['welcome','goal','habits'][n-1]}">→ חזרה</button><span>${n} מתוך 3 · בונים את האתגר שלך</span></div><div class="progress"><span style="width:${n/3*100}%"></span></div>`;
const quote=['לא צריך יום מושלם כדי לעשות צעד קטן.','הקצב שלך הוא מקום טוב להתחיל ממנו.','גם עשר דקות הן זמן שהקדשת לעצמך.','היום בונים על מה שכבר התחיל.','לפעמים ההישג הוא פשוט לחזור.','לא הכול בבת אחת. דבר אחד עכשיו.','שבוע של בחירות קטנות הוא כבר דרך.','מותר לדייק את היעד תוך כדי תנועה.','גם כשהיום עמוס, אפשר לפנות רגע.','מה שעוזר לך להתמיד שווה לשמור.','פחות להשוות. יותר לשים לב לעצמך.','כל סימון הוא רגע שבו בחרת בעצמך.','יום פחות מוצלח לא מוחק את הדרך.','עוד שבוע, ועוד הזדמנות ללמוד על עצמך.','הרגל קטן יכול למצוא מקום ביום גדול.','לא חייבים למהר כדי להתקדם.','להקשיב לעצמך זו גם התקדמות.','מה נעשה קצת יותר פשוט מאז ההתחלה?','אפשר להיות גאים גם בדברים הקטנים.','מחר מסכמים. היום עושים את הצעד של היום.','האתגר מסתיים. ההרגלים יכולים להישאר.'];
function art(ending=false){return `<svg class="art ${ending?'ending-art':''}" viewBox="0 0 350 205" role="img" aria-label="איור של שביל מתפתל בין גבעות ושער פתוח"><defs><linearGradient id="sky" x2="0" y2="1"><stop stop-color="#ecebe0"/><stop offset="1" stop-color="#f6f2e8"/></linearGradient><linearGradient id="door" x2="1" y2="1"><stop stop-color="#d1b588"/><stop offset="1" stop-color="#ece0c4"/></linearGradient></defs><rect x="4" y="4" width="342" height="195" rx="90" fill="url(#sky)"/><circle cx="251" cy="49" r="21" fill="#ddbe89"/><path d="M6 160Q79 70 171 142T344 111V179Q344 199 325 199H25Q5 199 6 180Z" fill="#dce3d6"/><path d="M6 168Q105 118 193 160T344 147V184Q344 199 328 199H23Q6 199 6 184Z" fill="#c3cfbf"/><path d="M151 199Q223 171 191 153T172 121" stroke="#f7f0df" stroke-width="23" fill="none"/><path d="M151 199Q223 171 191 153T172 121" stroke="#cfbda0" stroke-width="1" stroke-dasharray="3 8" fill="none"/><path d="M148 126V83a24 24 0 0 1 48 0v43Z" fill="#25394b"/><path d="M156 126V84a16 16 0 0 1 32 0v42Z" fill="#f8f2dd"/><path d="M156 126V84q0-17 17-16v48Z" fill="url(#door)"/><circle cx="167" cy="98" r="1.5" fill="#8c744f"/><path d="M59 140v-28m0 11-9-8m9 14 9-8M293 151v-26m0 11 8-9" stroke="#8c9e86" stroke-width="2" fill="none"/><g fill="#fff9e9"><circle cx="224" cy="92" r="2"/><circle cx="105" cy="72" r="2"/><circle cx="276" cy="101" r="1.5"/></g></svg>`;}
function navigate(to){const keepDay=(to==='reflection'&&page==='today')||(to==='contact'&&['today','reflection'].includes(page));previousPage=page;page=to;if(!keepDay)viewDay=null;render();screen.scrollTop=0;screen.querySelector('h2')?.focus({preventScroll:true});}
function ensureStart(){if(!model.start){model.start=calendarDate();save();}}
function render(){
 if(!active().length&&['rhythm','today','journey','reflection','summary','contact'].includes(page))page='habits';
 const meta=screens.find(s=>s[0]===page),index=screens.indexOf(meta);
 $('#stage-label').textContent=String(index+1).padStart(2,'0')+' / '+meta[1];$('#stage-title').innerHTML=meta[2];$('#stage-copy').textContent=meta[3];
 $('#preview').innerHTML=screens.map(([id,label],i)=>`<button data-go="${id}" ${id===page?'aria-current="step"':''} aria-label="מסך ${i+1}: ${label}">${String(i+1).padStart(2,'0')}</button>`).join('');
 const preview=$('#preview'),selectedPreview=preview.querySelector('[aria-current]');if(selectedPreview)preview.scrollLeft=selectedPreview.offsetLeft-preview.offsetLeft-preview.clientWidth/2+20;
 const tabItems=[['today','היום שלי'],['journey','הדרך שלי'],['reflection','סוגרים יום'],['rhythm','ההרגלים שלי']];
 const showTabs=model.start&&['today','journey','reflection','rhythm','summary','contact'].includes(page);
 $('#tabs').hidden=!showTabs;$('#tabs').innerHTML=tabItems.map(([id,label])=>`<button data-go="${id}" class="${id===page?'active':''}" ${id===page?'aria-current="page"':''}>${label}</button>`).join('');
 if(page==='welcome')screen.innerHTML=`<div class="center">${art()}${heading('21 יום.<br>קצת יותר בשבילך.')}<p class="intro-sub">בוחרים כמה הרגלים עם איתי.<br>ונותנים להם מקום, יום אחרי יום.</p><div class="three"><span><b>01</b>בוחרים</span><span><b>02</b>עושים</span><span><b>03</b>מסמנים</span></div></div>${actions(primary(model.start?'חוזרים ליום שלי':'בואו נתחיל',model.start?'today':'goal'),'<p class="tiny center">בלי מושלם. עם כוונה.</p>')}`;
 if(page==='goal')screen.innerHTML=setupStep(1)+heading('מה היית רוצה<br>לקחת מ־21 הימים האלה?')+`<form id="goal-form" class="grow"><label class="field">איך קוראים לך? <input id="name" autocomplete="given-name" maxlength="35" placeholder="השם שלך · לא חובה" value="${escapeHTML(model.name)}"></label><label class="field">בסוף האתגר אני רוצה…<textarea id="goal" maxlength="180" required placeholder="למשל: להרגיש שיש לי שגרה שאני מצליח להתמיד בה">${escapeHTML(model.goal)}</textarea></label><div class="suggestions"><button type="button" data-suggest="להרגיש יותר אנרגיה ביום שלי">יותר אנרגיה</button><button type="button" data-suggest="לבנות שגרה שאצליח להתמיד בה">להתמיד בשגרה</button><button type="button" data-suggest="לפנות זמן קבוע לעצמי">זמן לעצמי</button></div><details class="measurements"><summary>גובה ומשקל · אם זה רלוונטי למטרה שלך</summary><div class="two"><label class="field">גובה בס״מ<input id="height" type="number" inputmode="decimal" min="100" max="230" value="${escapeHTML(model.height)}"></label><label class="field">משקל בק״ג<input id="weight" type="number" inputmode="decimal" min="30" max="300" step="0.1" value="${escapeHTML(model.weight)}"></label></div></details><div class="actions"><button class="primary" type="submit">בוחרים הרגלים <span>←</span></button></div></form>`;
 if(page==='habits')screen.innerHTML=setupStep(2)+heading('במה מתחילים?')+`<p class="muted">אפשר לבחור הרגל אחד ועד חמישה.<br>את הכמות והזמן מדייקים במסך הבא.</p><div class="pick-list">${model.habits.map(h=>`<button class="pick" data-habit="${h.id}" aria-pressed="${model.selected.includes(h.id)}">${icon(h.id)}<span class="pick-copy"><strong>${escapeHTML(h.title)}</strong><small>${escapeHTML(h.hint||'הרגל אישי שלך')}</small></span><span class="check" aria-hidden="true">${model.selected.includes(h.id)?'✓':''}</span></button>`).join('')}</div><form id="custom-form" class="custom-input"><input id="custom" aria-label="הרגל משלי" maxlength="45" placeholder="או הרגל משלי…"><button type="submit" aria-label="הוספת הרגל אישי">＋</button></form><div class="status-message" id="pick-status" role="status">${model.selected.length} מתוך 5 נבחרו</div>${actions(`<button class="primary" data-action="rhythm" ${model.selected.length?'':'disabled'}>זה הכיוון שלי <span>←</span></button>`)}`;
 if(page==='rhythm')screen.innerHTML=(model.start?'<div class="step"><button class="back" data-go="today">→ חזרה ליום שלי</button><button class="text-button" data-go="habits">שינוי הרגלים</button></div>':setupStep(3))+heading('קטן, ברור.<br>ושלך.')+`<p class="muted">היעדים כאן הם נקודת פתיחה לדוגמה.<br>אפשר לשנות ולדייק יחד עם איתי.</p><form class="grow" id="rhythm-form">${active().map(h=>`<div class="habit-setting"><div class="row">${icon(h.id)}<h3>${escapeHTML(h.title)}</h3></div><label class="field">מה נחשב ״עשיתי״ בשבילך?<input name="target-${h.id}" required maxlength="90" value="${escapeHTML(h.target)}"></label><div class="reminder-row"><label><input type="checkbox" name="reminder-${h.id}" ${h.reminder?'checked':''}>תזכורת</label><input type="time" name="time-${h.id}" aria-label="שעת תזכורת עבור ${escapeHTML(h.title)}" value="${h.time}" required></div></div>`).join('')}<div class="notification-note">התזכורות מוצגות כאן להמחשה בלבד. לא נשלחות התראות למכשיר.</div><div class="actions"><button class="primary" type="submit">${model.start?'שומרים וחוזרים ליום שלי':'יוצאים לדרך'} <span>←</span></button></div></form>`;
 if(page==='today'){
 const d=shownDay(),done=countDone(d),all=done===active().length,r=record(d);
 screen.innerHTML=`<div class="row"><span class="eyebrow" style="margin:0">${model.name?escapeHTML(model.name)+', זה הזמן שלך':'זה הזמן שלך'}</span><button class="text-button" data-go="contact">בקשר עם איתי</button></div><div class="day-hero"><div>${heading(d===21?'הצעד של היום האחרון':'רק הצעד של היום.')}<p>${escapeHTML(model.goal||'לבנות שגרה שמתאימה לי')}</p></div><div class="day-ring"><div><b>${d}</b><small>מתוך 21 ימים</small></div></div></div><div class="row"><span class="section-heading">הדברים הקטנים שלי</span><span class="section-count">${done} מתוך ${active().length} להיום</span></div><div class="daily-list">${active().map(h=>`<button class="daily-task" data-check="${h.id}" aria-pressed="${r.checks.includes(h.id)}" aria-label="${escapeHTML(h.title)}: ${escapeHTML(h.target)}">${icon(h.id)}<span class="content"><strong>${escapeHTML(h.target)}</strong><small>${h.reminder?'תזכורת לדוגמה · '+h.time:escapeHTML(h.title)}</small></span><span class="circle" aria-hidden="true">${r.checks.includes(h.id)?'✓':''}</span></button>`).join('')}</div>${all?'<div class="reflection-stamp" role="status">כל ההרגלים שסימנת לעצמך להיום הושלמו. יפה שעשית מקום לעצמך.</div>':''}<div class="quote">${quote[d-1]}</div>${actions(primary(r.closed?'למשוב של היום':'סוגרים את היום','reflection'))}`;
 }
 if(page==='journey'){
 const s=stats(),day=currentDay();screen.innerHTML=heading('כל יום,<br>עוד דלת שנפתחת.','הדרך שלי')+`<p class="muted">גם יום שלא הספקת בו הכול נשאר חלק מהדרך.</p><div class="journey-grid">${Array.from({length:21},(_,i)=>{const d=i+1,r=record(d),finished=r.checks.length>0&&countDone(d)===active().length;return `<button class="door ${d===day?'today':''} ${d<day?'open':''} ${finished?'done':''}" data-day="${d}" ${d>day?'disabled':''} aria-label="יום ${d}${d>day?', עדיין לא נפתח':finished?', כל ההרגלים הושלמו':d===day?', היום':''}"><span>${String(d).padStart(2,'0')}</span><small>${finished?'✓':d===day?'היום':d>day?'·':''}</small></button>`;}).join('')}</div><div class="legend"><span>היום</span><span>הושלם</span><span>בהמשך</span></div><div class="stats"><div class="stat"><b>${s.days}</b><span>ימים עם עשייה</span></div><div class="stat"><b>${s.checks}</b><span>צעדים שסומנו</span></div><div class="stat"><b>${s.closed}</b><span>סיכומים אישיים</span></div></div><div class="panel"><h3>המטרה שלקחת איתך</h3><p>${escapeHTML(model.goal||'לבנות שגרה שמתאימה לי')}</p></div>${actions(primary(day===21?'לסיכום הדרך':'חוזרים ליום שלי',day===21?'summary':'today'))}`;
 }
 if(page==='reflection'){
 const d=shownDay(),weekly=d===7||d===14,r=record(d);screen.innerHTML=`<div class="step"><button class="back" data-go="today">→ חזרה</button><span>יום ${d} מתוך 21</span></div>`+heading(weekly?'מרימים רגע את הראש.':'איך היה לך היום?',weekly?'סיכום שבועי':'רגע לעצמך')+`<p class="muted">${weekly?'מה עבד בשבילך השבוע, ומה כדאי לשנות?':'אין ציון. רק רגע לשים לב למה שהיה.'}</p><div class="moods">${['היה מאתגר','היה בסדר','היה טוב'].map((m,n)=>`<button data-mood="${n}" aria-pressed="${r.mood===n}">${m}</button>`).join('')}</div><form id="reflection-form" class="grow"><label class="field">${weekly?'מה לקחת מהשבוע הזה?':'משהו קטן שחשוב לי לזכור'}<textarea id="reflection-note" maxlength="600" placeholder="אפשר גם משפט אחד…">${escapeHTML(r.note)}</textarea></label><p class="tiny">הכתיבה היא בשבילך. שיתוף עם איתי נעשה רק אם בוחרים לשלוח.</p><div class="actions"><button type="submit" class="primary">שומרים את הרגע <span>✓</span></button>${weekly?secondary('לשתף סיכום עם איתי','contact'):''}</div><p id="reflection-status" class="toast" role="status">${r.closed?'הסיכום שלך שמור במכשיר הזה.':''}</p></form>`;
 }
 if(page==='summary'){
 const s=stats();screen.innerHTML=`<div class="center">${art(true)}${heading(currentDay()===21?'21 יום.<br>ומה עכשיו?':'הדרך שלך, עד עכשיו.')}<p class="muted">הדברים הקטנים שעשית הם שלך.<br>אפשר לקחת אותם גם הלאה.</p></div><div class="stats"><div class="stat"><b>${s.days}</b><span>ימים עם עשייה</span></div><div class="stat"><b>${s.checks}</b><span>צעדים קטנים</span></div><div class="stat"><b>${active().length}</b><span>הרגלים שבחרת</span></div></div><div class="summary-list">${active().map(h=>`<div class="summary-item"><span>${escapeHTML(h.title)}</span><b>${Object.values(records()).filter(r=>r.checks.includes(h.id)).length} סימונים</b></div>`).join('')}</div><p class="journey-note">${demoDay?'זו תצוגת סוף האתגר. המספרים משקפים רק סימונים שבוצעו בהמחשה.':'הסיכום מבוסס על הסימונים שלך במכשיר הזה.'}</p>${actions(primary('לחשוב עם איתי על ההמשך','contact'),secondary('לדרך שלי','journey'))}`;
 }
 if(page==='contact'){
 const s=stats();screen.innerHTML=`<div class="step"><button class="back" data-go="today">→ חזרה</button><span>עם איתי</span></div>`+heading('יש עם מי<br>לעשות את הצעד הבא.')+`<p class="muted">שאלה קטנה באמצע, סיכום של השבוע או מחשבה על המשך ליווי — אפשר לפתוח שיחה.</p><div class="panel"><span class="tag">סיכום אישי לשיתוף</span><h3 style="margin-top:14px">${escapeHTML(model.goal||'אתגר 21 יום')}</h3><p>יום ${shownDay()} · ${s.days} ימים עם עשייה · ${s.checks} סימונים</p></div><label class="field">משהו להוסיף?<textarea id="message" maxlength="500" placeholder="היי איתי, רציתי לשתף…"></textarea></label><p class="tiny">ייפתח WhatsApp עם טיוטה שתוכל לערוך. שום דבר לא נשלח אוטומטית.</p>${actions(primary('פתיחת שיחה עם איתי','share'))}`;
 }
 if(demoDay&&['today','journey','reflection','summary','contact'].includes(page))screen.insertAdjacentHTML('afterbegin',`<div class="demo-state">מציגים יום ${demoDay} להמחשה · הנתונים נפרדים מהאתגר שלך</div>`);
 if(!storageWorks)screen.insertAdjacentHTML('beforeend','<p class="toast" role="status">השמירה במכשיר אינה זמינה בדפדפן הזה. השינויים יישארו רק כל עוד העמוד פתוח.</p>');
}
function modal(html){$('#dialog-content').innerHTML=html;$('#dialog').showModal();}
document.addEventListener('click',e=>{
 const b=e.target.closest('button');if(!b)return;
 if(b.dataset.go){navigate(b.dataset.go);return;}
 if(b.dataset.suggest){$('#goal').value=b.dataset.suggest;$('#goal').setCustomValidity('');return;}
 if(b.dataset.habit){const id=b.dataset.habit;if(model.selected.includes(id))model.selected=model.selected.filter(h=>h!==id);else if(model.selected.length<5)model.selected.push(id);else{$('#pick-status').textContent='עד חמישה הרגלים. אפשר להסיר אחד כדי לבחור אחר.';return;}save();render();return;}
 if(b.dataset.check){ensureStart();const r=record(),id=b.dataset.check,checks=r.checks.includes(id)?r.checks.filter(h=>h!==id):[...r.checks,id];updateRecord({checks});const position=screen.scrollTop;render();screen.scrollTop=position;return;}
 if(b.dataset.day){viewDay=Number(b.dataset.day);page='today';render();screen.scrollTop=0;return;}
 if(b.dataset.mood){const note=$('#reflection-note').value;updateRecord({mood:Number(b.dataset.mood),note});render();return;}
 const a=b.dataset.action;
 if(screens.some(s=>s[0]===a)){navigate(a);return;}
 if(a==='about')modal('<h2>21 עם איתי · המחשה</h2><p>כיוון למוצר מתוך השיחה עם איתי: אתגר אישי, הרגלים לבחירה ומעקב יומי פשוט.</p><p>הנתונים נשמרים רק בדפדפן הזה. אין חשבון משותף, סנכרון למאמן או התראות אמיתיות. יעדי הדוגמה והמשפטים היומיים הם הצעת תוכן, ולא הנחיות שאיתי אישר.</p><p>בתפריט שמתחת למסך אפשר להציג את יום 7 ואת יום 21. נתוני ההמחשה נפרדים מהאתגר האישי שלך.</p>');
 if(a==='close')$('#dialog').close();
 if(a==='reset')modal('<h2>להתחיל מחדש?</h2><p>הפעולה תמחק את המטרה והסימונים השמורים בדמו הזה בלבד.</p><button class="primary" data-action="confirm-reset">כן, לאפס את הדוגמה</button>');
 if(a==='confirm-reset'){model=fresh();demoDay=0;demoRecords={};viewDay=null;$('#demo-day').value='0';save();$('#dialog').close();navigate('welcome');}
 if(a==='share'){const s=stats(),r=record(),addition=$('#message').value;const text=`היי איתי, רציתי לשתף מהאתגר של 21 הימים.\nהמטרה שלי: ${model.goal||'לבנות שגרה שמתאימה לי'}\nיום ${shownDay()} · ${s.days} ימים עם עשייה · ${s.checks} סימונים.\n${r.note?'מחשבה מהיום: '+r.note+'\n':''}${addition}${demoDay?'\n(סיכום מתוך המחשה)':''}`;window.open('https://wa.me/972559277324?text='+encodeURIComponent(text),'_blank','noopener');}
});
document.addEventListener('submit',e=>{
 e.preventDefault();
 if(e.target.id==='goal-form'){model.name=$('#name').value.trim();model.goal=$('#goal').value.trim();if(!model.goal){$('#goal').setCustomValidity('אפשר לכתוב מטרה קצרה או לבחור הצעה.');$('#goal').reportValidity();return;}model.height=$('#height').value;model.weight=$('#weight').value;save();navigate('habits');}
 if(e.target.id==='custom-form'){const title=$('#custom').value.trim();if(!title)return;if(model.selected.length>=5){$('#pick-status').textContent='אפשר לבחור עד חמישה הרגלים. הסר אחד כדי להוסיף הרגל אישי.';return;}const id='custom-'+Date.now();model.habits.push({id,title,hint:'הרגל אישי',target:title,time:'20:00',reminder:false});model.selected.push(id);save();render();}
 if(e.target.id==='rhythm-form'){const form=new FormData(e.target);for(const h of active()){h.target=String(form.get('target-'+h.id)).trim();h.time=String(form.get('time-'+h.id));h.reminder=form.has('reminder-'+h.id);}ensureStart();save();navigate('today');}
 if(e.target.id==='reflection-form'){updateRecord({note:$('#reflection-note').value.trim(),closed:true});$('#reflection-status').textContent=demoDay?'נשמר בהמחשה. מחר יש עוד הזדמנות קטנה.':storageWorks?'שמור במכשיר שלך. מחר יש עוד הזדמנות קטנה.':'נשמר בעמוד הפתוח בלבד. השמירה במכשיר אינה זמינה.';}
});
document.addEventListener('input',e=>{if(e.target.id==='goal')e.target.setCustomValidity('');});
$('#demo-day').addEventListener('change',e=>{demoDay=Number(e.target.value);viewDay=null;navigate(demoDay===21?'summary':demoDay===7?'journey':'today');});
render();
