const $=s=>document.querySelector(s);
const escapeHTML=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const KEY='maklef-21-demo-v1';
const icons={nutrition:'<path d="M4 3v7m3-7v7m-6-7v7h6M4 10v11M15 3v18m0-18c6 2 6 9 0 9"/>',move:'<path d="m3 16 4-4 4 3 4-8 6 3M7 12l-3-2m7 5-3 6m7-14 1-4"/><circle cx="17" cy="3" r="1.5"/>',water:'<path d="M12 3S5 11 5 15a7 7 0 0 0 14 0c0-4-7-12-7-12Z"/><path d="M9 15a3 3 0 0 0 3 3"/>',read:'<path d="M12 6c-3-3-7-3-9-2v15c3-1 6-1 9 1 3-2 6-2 9-1V4c-2-1-6-1-9 2Zm0 0v14"/>',write:'<path d="m4 16 12-12 4 4L8 20H4v-4Zm9-9 4 4M4 22h16"/>',sleep:'<path d="M20 15A9 9 0 0 1 9 4a9 9 0 1 0 11 11Z"/>',custom:'<path d="m12 3 2.7 5.5 6.1.9-4.4 4.3 1 6.1L12 17l-5.4 2.8 1-6.1-4.4-4.3 6.1-.9Z"/>'};
const icon=id=>`<span class="icon" aria-hidden="true"><svg viewBox="0 0 24 24">${icons[id]||icons.custom}</svg></span>`;
const catalog=[{id:'move',title:'אימון',hint:'הליכה, ריצה או כוח',target:'30 דקות הליכה',time:'18:00'},{id:'nutrition',title:'תזונה',hint:'לפי התוכנית האישית',target:'להכין ארוחה אחת לפי התוכנית שלי',time:'19:00'},{id:'water',title:'מים',hint:'יעד שתייה אישי לאורך היום',target:'למלא בקבוק מים אחד לקראת היום',time:'12:00'},{id:'read',title:'קריאה',hint:'כמה עמודים ביום',target:'10 עמודים',time:'22:00'},{id:'write',title:'כתיבה',hint:'כמה שורות על היום',target:'3 שורות על היום',time:'21:00'},{id:'sleep',title:'שינה',hint:'ללכת לישון בשעה קבועה',target:'במיטה עד 22:30',time:'22:00'}];
const fresh=()=>({name:'',age:'',goal:'',barrier:'',keepHabit:'',height:'',weight:'',selected:['move','read'],habits:catalog.map(h=>({...h,reminder:false})),start:null,records:{}});
let model=fresh(),storageWorks=true;
try{const saved=JSON.parse(localStorage.getItem(KEY)||'null');if(saved&&Array.isArray(saved.habits)&&Array.isArray(saved.selected)&&saved.records)model=saved;}catch{storageWorks=false;}
// Refresh catalog labels without overwriting personal targets or recorded progress.
for(const h of catalog){const saved=model.habits.find(x=>x.id===h.id);if(saved){saved.title=h.title;saved.hint=h.hint;}else model.habits.push({...h,reminder:false});}
let page=model.start?'today':'welcome',demoDay=0,demoRecords={},viewDay=null,previousPage=page;
const calendarDate=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
function dateNumber(date){const [y,m,d]=date.split('-').map(Number);return Date.UTC(y,m-1,d)/86400000;}
function realDay(){return model.start?Math.max(1,Math.min(21,Math.floor(dateNumber(calendarDate())-dateNumber(model.start))+1)):1;}
const currentDay=()=>demoDay||realDay();
const shownDay=()=>viewDay||currentDay();
const records=()=>demoDay?demoRecords:model.records;
const active=()=>model.habits.filter(h=>model.selected.includes(h.id));
const record=(day=shownDay())=>records()[day]||{checks:[],mood:null,note:'',closed:false};
function save(){try{localStorage.setItem(KEY,JSON.stringify(model));storageWorks=true;}catch{storageWorks=false;}}
function updateRecord(change){const d=shownDay();records()[d]={...record(d),...change};if(!demoDay)save();}
const countDone=day=>active().filter(h=>record(day).checks.includes(h.id)).length;
const stats=()=>({checks:Object.values(records()).reduce((n,r)=>n+active().filter(h=>r.checks.includes(h.id)).length,0),days:Object.values(records()).filter(r=>active().some(h=>r.checks.includes(h.id))).length,closed:Object.values(records()).filter(r=>r.closed).length});
function streak(){let d=currentDay(),n=0;if(!countDone(d))d--;while(d>0&&countDone(d)>0){n++;d--;}return n;}
const reminderText=h=>`${h.title}. ${h.target}. אחר כך מסמנים.`;
const screens=[['welcome','התחלה קטנה','21 יום.<br>בונים משמעת.','בוחרים הרגלים. עושים. מסמנים. כל יום.'],['age','היכרות','מתחילים בקלות.<br>בחירה אחת בכל מסך.','בלי למלא טופס. פשוט בוחרים וממשיכים.'],['height','גובה','מחליקים.<br>בוחרים. ממשיכים.','בורר גובה נוח, בלי לפתוח מקלדת.'],['weight','משקל','נקודת הפתיחה שלך.<br>בקצב שלך.','אפשר לבחור בגלילה, ואפשר לדלג.'],['goal','מטרה אישית','מה המטרה שלך<br>באתגר?','בוחרים כיוון. אפשר לדייק אותו בהמשך.'],['barrier','מה עוצר אותי','מזהים מה עוצר.<br>בונים דרך להתמיד.','בחירה קצרה לפני שמגדירים את ההרגלים.'],['habits','ההרגלים שלי','לא חייבים חמישה.<br>אפשר להתחיל מאחד.','בוחרים הרגלים שמתאימים לאדם, לא להפך.'],['rhythm','הקצב שלי','יעד ברור.<br>שעה קבועה.','לכל הרגל יעד ברור ושעה לבחירתך.'],['today','היום שלי','פחות לחשוב.<br>יותר פשוט לעשות.','היעדים מול העיניים. מסמנים אחרי שעושים.'],['journey','21 הדלתות','כל יום נפתחת<br>עוד דלת.','רואים את הדרך שעברת ואת מה שעוד לפניך.'],['reflection','סגירת יום','מה עבד?<br>מה משנים?','משוב קצר במקום עוד טופס.'],['summary','ממשיכים מכאן','21 יום הם התחלה.<br>מה לוקחים הלאה?','סיכום אישי ואפשרות להמשיך לליווי עם איתי.'],['contact','בקשר עם איתי','מדברים<br>עם איתי.','אפשר לפתוח שיחה עם סיכום אישי, ולשלוח כשמוכנים.']];
const screen=$('#screen');
const primary=(label,action)=>`<button class="primary" type="button" data-action="${action}">${label}<span aria-hidden="true">←</span></button>`;
const secondary=(label,action)=>`<button class="secondary" type="button" data-action="${action}">${label}</button>`;
const heading=(text,eyebrow='')=>`${eyebrow?`<div class="eyebrow">${eyebrow}</div>`:''}<h2 tabindex="-1">${text}</h2>`;
const actions=(...content)=>`<div class="actions">${content.join('')}</div>`;
const setupStep=()=>{const order=['age','height','weight','goal','barrier','habits','rhythm'],i=order.indexOf(page);return `<div class="step"><button class="back" data-go="${i>0?order[i-1]:'welcome'}">→ חזרה</button><span>${i+1} מתוך 7 · ההתחלה שלך</span></div><div class="progress"><span style="width:${(i+1)/7*100}%"></span></div>`;};
const quote=['לא צריך להרגיש מוכנים. צריך להתחיל.', 'משמעת זה לעשות גם כשאין הרבה חשק.', 'יום 3. ממשיכים עם מה שקבענו.', 'קטן ועקבי מנצח גדול ופעם אחת.', 'היעד ברור. השעה ביומן. עכשיו עושים.', 'מסמנים מה שעשינו. רואים מה צריך לשפר.', 'שבוע אחד בפנים. עוד שניים.', 'לא מחכים למוטיבציה. חוזרים לתוכנית.', 'גם יום חלקי הוא יום שעשינו בו משהו.', 'מה עזר עד עכשיו? לוקחים את זה גם להיום.', 'חצי דרך. זמן לראות מה עובד ומה צריך לדייק.', 'פספסת אתמול? היום אפשר לחזור.', 'לא חייבים לחכות ליום פנוי. קובעים זמן ביומן.', 'שבועיים בפנים. מה כבר קל יותר לעשות?', 'יום קשה? מתאימים את היעד למציאות, יחד עם איתי.', 'גם מנוחה לפי התוכנית היא חלק ממשמעת.', 'הרגלים מתרגלים גם בימים רגילים.', 'קודם עושים. אחר כך מסמנים.', 'קו הסיום קרוב. ממשיכים לפי התוכנית.', 'מחר מסכמים. היום עושים את מה שקבענו.', 'יום 21. מה ממשיכים לעשות גם מחר?'];
function art(ending=false){return `<svg class="art ${ending?'ending-art':''}" viewBox="0 0 350 205" role="img" aria-label="איור של שביל מתפתל בין גבעות ושער פתוח"><defs><linearGradient id="sky" x2="0" y2="1"><stop stop-color="#ecebe0"/><stop offset="1" stop-color="#f6f2e8"/></linearGradient><linearGradient id="door" x2="1" y2="1"><stop stop-color="#d1b588"/><stop offset="1" stop-color="#ece0c4"/></linearGradient></defs><rect x="4" y="4" width="342" height="195" rx="90" fill="url(#sky)"/><circle cx="251" cy="49" r="21" fill="#ddbe89"/><path d="M6 160Q79 70 171 142T344 111V179Q344 199 325 199H25Q5 199 6 180Z" fill="#dce3d6"/><path d="M6 168Q105 118 193 160T344 147V184Q344 199 328 199H23Q6 199 6 184Z" fill="#c3cfbf"/><path d="M151 199Q223 171 191 153T172 121" stroke="#f7f0df" stroke-width="23" fill="none"/><path d="M151 199Q223 171 191 153T172 121" stroke="#cfbda0" stroke-width="1" stroke-dasharray="3 8" fill="none"/><path d="M148 126V83a24 24 0 0 1 48 0v43Z" fill="#25394b"/><path d="M156 126V84a16 16 0 0 1 32 0v42Z" fill="#f8f2dd"/><path d="M156 126V84q0-17 17-16v48Z" fill="url(#door)"/><circle cx="167" cy="98" r="1.5" fill="#8c744f"/><path d="M59 140v-28m0 11-9-8m9 14 9-8M293 151v-26m0 11 8-9" stroke="#8c9e86" stroke-width="2" fill="none"/><g fill="#fff9e9"><circle cx="224" cy="92" r="2"/><circle cx="105" cy="72" r="2"/><circle cx="276" cy="101" r="1.5"/></g></svg>`;}
function navigate(to){const keepDay=(to==='reflection'&&page==='today')||(to==='contact'&&['today','reflection'].includes(page));previousPage=page;page=to;if(!keepDay)viewDay=null;render();screen.scrollTop=0;screen.querySelector('h2')?.focus({preventScroll:true});}
function ensureStart(){if(!model.start){model.start=calendarDate();save();}}
function render(){
 if(!active().length&&['rhythm','today','journey','reflection','summary','contact'].includes(page))page='habits';
 const meta=screens.find(s=>s[0]===page),index=screens.indexOf(meta);
 $('#stage-label').textContent=String(index+1).padStart(2,'0')+' / '+meta[1];$('#stage-title').innerHTML=meta[2];$('#stage-copy').textContent=meta[3];
 $('#preview').innerHTML=screens.map(([id,label],i)=>`<button data-go="${id}" ${id===page?'aria-current="step"':''} aria-label="מסך ${i+1}: ${label}">${String(i+1).padStart(2,'0')}</button>`).join('');
 const preview=$('#preview'),selectedPreview=preview.querySelector('[aria-current]');if(selectedPreview)preview.scrollLeft=selectedPreview.offsetLeft-preview.offsetLeft-preview.clientWidth/2+20;
 const tabItems=[['today','היום שלי'],['journey','הדרך שלי'],['reflection','סוגרים יום'],['rhythm','ההרגלים שלי']];
 const showTabs=model.start&&['today','journey','reflection','rhythm','summary','contact'].includes(page);
 $('#tabs').hidden=!showTabs;$('#tabs').innerHTML=tabItems.map(([id,label])=>`<button data-go="${id}" class="${id===page?'active':''}" ${id===page?'aria-current="page"':''}>${label}</button>`).join('');
 if(page==='welcome')screen.innerHTML=`<div class="center welcome">${art()}${heading('21 יום של משמעת','עם איתי מקלף')}<p class="brand-line">משמעת חזקה,<br>בלי יותר מדי מוטיבציה.</p><p class="intro-sub">בוחרים הרגלים. עושים. מסמנים. כל יום.</p></div>${actions(primary(model.start?'חוזרים להיום':'מתחילים',model.start?'today':'age'),'<button class="install-link" data-action="about">על הדמו</button>')}`;
 if(page==='age')screen.innerHTML=setupStep()+scene('age')+heading('באיזה טווח גילאים?')+`<p class="muted">מתחילים בהיכרות קצרה.</p><div class="age-grid">${['מתחת ל־18','18–24','25–34','35–44','45–54','55+'].map(x=>`<button class="age-choice" data-age="${x}" aria-pressed="${model.age===x}">${x}<span>←</span></button>`).join('')}</div><p class="tiny center tap-hint">בוחרים אפשרות וממשיכים אוטומטית</p>${actions(secondary('לדלג בינתיים','height'))}`;
 if(page==='height'||page==='weight'){
 const height=page==='height',key=page,unit=height?'ס״מ':'ק״ג';
 screen.innerHTML=setupStep()+scene(key)+heading(height?'מה הגובה שלך?':'ומה המשקל שלך?')+`<p class="muted center">מחליקים את המספרים למעלה או למטה.</p>${measurementWheel(key,height?100:30,height?230:300,height?1:.5,height?175:75,unit)}${actions(primary('ממשיכים','save-measure'),secondary('לדלג בינתיים','skip-measure'))}`;
 }
 if(page==='goal')screen.innerHTML=setupStep()+scene('goal')+heading('מה המטרה שלך<br>ל־21 הימים הקרובים?')+`<div class="goal-choices">${[['להתמיד באימונים','move'],['לשפר את השינה','sleep'],['להרגיש יותר אנרגיה','custom'],['להתקדם ליעד המשקל שלי','nutrition']].map(([x,id])=>`<button class="goal-choice" data-goal="${x}">${icon(id)}<strong>${x}</strong><span>←</span></button>`).join('')}</div><details class="custom-goal"><summary>יש לי מטרה אחרת</summary><form id="goal-form"><label class="field">המטרה שלי<textarea id="goal" required maxlength="180" placeholder="במילים שלך">${escapeHTML(model.goal)}</textarea></label><button class="primary" type="submit">ממשיכים ←</button></form></details>`;
 if(page==='barrier')screen.innerHTML=setupStep()+scene('barrier')+heading('מה בדרך כלל<br>עוצר אותך באמצע?')+`<div class="goal-choices">${['עומס ביום־יום','קשה למצוא זמן','נגמר החשק','יום רע שהופך לשבוע'].map(x=>`<button class="goal-choice" data-barrier="${x}"><strong>${x}</strong><span>←</span></button>`).join('')}</div>${actions(secondary('לדלג לבחירת ההרגלים','habits'))}`;

 if(page==='habits')screen.innerHTML=setupStep(2)+heading('על מה עובדים<br>21 יום?')+`<p class="muted">עד 5 הרגלים שסיכמת עם איתי.<br>גם אחד מספיק.</p><div class="pick-list">${model.habits.map(h=>`<button class="pick" data-habit="${h.id}" aria-pressed="${model.selected.includes(h.id)}">${icon(h.id)}<span class="pick-copy"><strong>${escapeHTML(h.title)}</strong><small>${escapeHTML(h.hint||'הרגל אישי שלך')}</small></span><span class="check" aria-hidden="true">${model.selected.includes(h.id)?'✓':''}</span></button>`).join('')}</div><form id="custom-form" class="custom-input"><input id="custom" aria-label="הרגל משלי" maxlength="45" placeholder="או הרגל משלי…"><button type="submit" aria-label="הוספת הרגל אישי">＋</button></form><div class="status-message" id="pick-status" role="status">${model.selected.length} מתוך 5 נבחרו</div>${actions(`<button class="primary" data-action="rhythm" ${model.selected.length?'':'disabled'}>מגדירים יעדים <span>←</span></button>`)}`;
 if(page==='rhythm')screen.innerHTML=(model.start?'<div class="step"><button class="back" data-go="today">→ חזרה ליום שלי</button><button class="text-button" data-go="habits">שינוי הרגלים</button></div>':setupStep(3))+heading('יעד ותזכורת')+`<p class="muted">לכל הרגל יעד שאפשר לסמן כבוצע.<br>הדוגמאות ניתנות לעריכה לפי התוכנית האישית.</p><form class="grow" id="rhythm-form">${active().map(h=>`<div class="habit-setting"><div class="row">${icon(h.id)}<h3>${escapeHTML(h.title)}</h3></div><label class="field">מה נחשב ״עשיתי״?<input name="target-${h.id}" required maxlength="90" value="${escapeHTML(h.target)}"></label><div class="reminder-row"><label><input type="checkbox" name="reminder-${h.id}" ${h.reminder?'checked':''}>תזכורת</label><input type="time" name="time-${h.id}" aria-label="שעת תזכורת עבור ${escapeHTML(h.title)}" value="${h.time}" required></div><div class="reminder-preview" data-reminder-preview="${h.id}" ${h.reminder?'':'hidden'}><span>תצוגת תזכורת · <b data-preview-time>${h.time}</b></span><strong data-preview-text>${escapeHTML(reminderText(h))}</strong></div></div>`).join('')}<div class="reminder-preview"><span>סיכום היום · תזכורת לדוגמה · 21:30</span><strong>עוד לא סימנת את היום? זה הזמן לבדוק מה בוצע.</strong></div><div class="notification-note">כך ייראו התזכורות. בדמו לא נשלחות התראות למכשיר.</div><div class="actions"><button class="primary" type="submit">${model.start?'שומרים וחוזרים ליום שלי':'מתחילים את יום 1'} <span>←</span></button></div></form>`;
 if(page==='today'){
 const d=shownDay(),done=countDone(d),all=done===active().length,r=record(d);
 screen.innerHTML=`<div class="row"><span class="eyebrow" style="margin:0">${model.name?'היי '+escapeHTML(model.name):'האתגר שלי'}</span><button class="text-button" data-go="contact">בקשר עם איתי</button></div><div class="day-hero"><div>${heading(`יום ${d} מתוך 21`)}<p>המטרה שלי: ${escapeHTML(model.goal||'לבנות שגרה שמתאימה לי')}</p></div><div class="day-ring"><div><b>${d}</b><small>מתוך 21 ימים</small></div></div></div><div class="quote daily-quote">${quote[d-1]}</div><div class="row"><span class="section-heading">ההרגלים שלי להיום</span><span class="section-count">היום: ${done} מתוך ${active().length}</span></div><div class="daily-list">${active().map(h=>`<button class="daily-task" data-check="${h.id}" aria-pressed="${r.checks.includes(h.id)}" aria-label="${escapeHTML(h.title)}: ${escapeHTML(h.target)}">${icon(h.id)}<span class="content"><strong>${escapeHTML(h.target)}</strong><small>${h.reminder?'תזכורת לדוגמה · '+h.time:escapeHTML(h.title)}</small></span><span class="circle" aria-hidden="true">${r.checks.includes(h.id)?'✓':''}</span></button>`).join('')}</div>${all?`<div class="reflection-stamp" role="status">${d===21?'כל היעדים של היום סומנו. לסיכום האתגר!':'היום סגור. נתראה מחר.'}</div>`:done>0?`<div class="partial-day" role="status">${done} מתוך ${active().length}. גם זה יום שנספר.</div>`:''}${actions(primary(r.closed?'לסיכום ששמרתי':'סיכום היום','reflection'))}`;
 }
 if(page==='journey'){
 const s=stats(),day=currentDay();screen.innerHTML=heading('כל יום נפתחת<br>עוד דלת.','הדרך שלי')+`<p class="muted">גם יום שלא הספקת בו הכול נשאר חלק מהדרך.</p><div class="journey-grid">${Array.from({length:21},(_,i)=>{const d=i+1,r=record(d),finished=r.checks.length>0&&countDone(d)===active().length;return `<button class="door ${d===day?'today':''} ${d<day?'open':''} ${finished?'done':''}" data-day="${d}" ${d>day?'disabled':''} aria-label="יום ${d}${d>day?', עדיין לא נפתח':finished?', כל ההרגלים הושלמו':d===day?', היום':''}"><span>${String(d).padStart(2,'0')}</span><small>${finished?'✓':d===day?'היום':d>day?'·':''}</small></button>`;}).join('')}</div><div class="legend"><span>היום</span><span>כל היעדים הושלמו</span><span>בהמשך</span></div><div class="stats"><div class="stat"><b>${s.days}</b><span>ימים עם עשייה</span></div><div class="stat"><b>${s.checks}</b><span>הרגלים שסומנו</span></div><div class="stat"><b>${streak()}</b><span>ימים ברצף</span></div></div><p class="tiny">רצף = ימים עם לפחות הרגל אחד שסומן. היום נשאר פתוח עד חצות.</p><div class="panel"><h3>המטרה שלי</h3><p>${escapeHTML(model.goal||'לבנות שגרה שמתאימה לי')}</p></div>${actions(primary(day===21?'לסיכום הדרך':'חזרה להיום',day===21?'summary':'today'))}`;
 }
 if(page==='reflection'){
 const d=shownDay(),weekly=d===7||d===14,r=record(d);screen.innerHTML=`<div class="step"><button class="back" data-go="today">→ חזרה</button><span>יום ${d} מתוך 21</span></div>`+heading(weekly?(d===7?'שבוע אחד בפנים.<br>איך הולך?':'שבועיים בפנים.<br>איך הולך?'):'איך הלך היום?',weekly?'סיכום שבועי':'סיכום היום')+`<p class="muted">${weekly?'מה שומרים, ומה משפרים לשבוע הבא?':'מה עבד, ומה אפשר לעשות אחרת מחר?'}</p><div class="moods">${['היה מאתגר','היה בסדר','היה טוב'].map((m,n)=>`<button data-mood="${n}" aria-pressed="${r.mood===n}">${m}</button>`).join('')}</div><form id="reflection-form" class="grow"><label class="field">${weekly?'מה עבד השבוע?':'מה חשוב לי לזכור מהיום?'}<textarea id="reflection-note" maxlength="600" placeholder="אפשר גם משפט אחד…">${escapeHTML(r.note)}</textarea></label>${weekly?`<label class="field">מה משנים לשבוע הבא?<textarea id="reflection-next" maxlength="400" placeholder="שינוי אחד שאפשר לנסות…">${escapeHTML(r.next||'')}</textarea></label>`:''}<p class="tiny">הסיכום אישי. איתי רואה אותו רק אם שולחים.</p><div class="actions"><button type="submit" class="primary">שומרים סיכום <span>✓</span></button>${weekly?secondary('משתפים את איתי','contact'):''}</div><p id="reflection-status" class="toast" role="status">${r.closed?'הסיכום שלך שמור במכשיר הזה.':''}</p></form>`;
 }
 if(page==='summary'){
 const s=stats();screen.innerHTML=`<div class="center">${art(true)}${heading(currentDay()===21?(s.days===21?'21 יום.<br>עשית את זה.':'21 יום.<br>מה לוקחים הלאה?'):'האתגר שלך, עד עכשיו.')}<p class="muted">הנה מה שסימנת במהלך האתגר.</p></div><div class="stats"><div class="stat"><b>${s.days}</b><span>ימים עם עשייה</span></div><div class="stat"><b>${s.checks}</b><span>הרגלים שסומנו</span></div><div class="stat"><b>${active().length}</b><span>הרגלים שבחרת</span></div></div><div class="summary-list">${active().map(h=>`<div class="summary-item"><span>${escapeHTML(h.title)}</span><b>${Object.values(records()).filter(r=>r.checks.includes(h.id)).length} סימונים</b></div>`).join('')}</div><label class="field">עם איזה הרגל ממשיכים מכאן?<select id="keep-habit"><option value="">בוחרים הרגל</option>${active().map(h=>`<option value="${h.id}" ${model.keepHabit===h.id?'selected':''}>${escapeHTML(h.title)}</option>`).join('')}</select></label><p id="keep-status" class="tiny" role="status"></p><p class="journey-note">${demoDay?'זו תצוגת סוף האתגר. המספרים משקפים רק סימונים שבוצעו בהמחשה.':'הסיכום מבוסס על הסימונים שלך במכשיר הזה.'}</p>${actions(primary('להמשיך עם איתי בליווי אישי','contact'),secondary('לצפייה באתגר שלי','journey'))}`;
 }
 if(page==='contact'){
 const s=stats();screen.innerHTML=`<div class="step"><button class="back" data-go="today">→ חזרה</button><span>עם איתי</span></div>`+heading('מדברים עם איתי')+`<p class="muted">יש שאלה או משהו שחשוב לשתף?</p><div class="panel"><span class="tag">הסיכום שלי</span><h3 style="margin-top:14px">${escapeHTML(model.goal||'אתגר 21 יום')}</h3><p>יום ${shownDay()} · ${s.days} ימים עם עשייה · ${s.checks} סימונים</p></div><label class="field">ההודעה שלי לאיתי:<textarea id="message" maxlength="500" placeholder="היי איתי, רציתי לשתף…"></textarea></label><p class="tiny">ההודעה תיפתח בוואטסאפ לעריכה. שולחים רק כשמוכנים.</p>${actions(primary('ממשיכים לוואטסאפ','share'))}`;
 }
 if(['age','height','weight','goal','barrier'].includes(page))screen.classList.add('onboarding');else screen.classList.remove('onboarding');
 if(['habits','rhythm','reflection','contact'].includes(page))screen.querySelector('h2')?.insertAdjacentHTML('beforebegin',scene(page,true));
 if(page==='height'||page==='weight')initWheel();
 if(demoDay&&['today','journey','reflection','summary','contact'].includes(page))screen.insertAdjacentHTML('afterbegin',`<div class="demo-state">מציגים יום ${demoDay} להמחשה · הנתונים נפרדים מהאתגר שלך</div>`);
 if(!storageWorks)screen.insertAdjacentHTML('beforeend','<p class="toast" role="status">השמירה במכשיר אינה זמינה בדפדפן הזה. השינויים יישארו רק כל עוד העמוד פתוח.</p>');
}
function modal(html){$('#dialog-content').innerHTML=html;$('#dialog').showModal();}
document.addEventListener('click',e=>{
 const b=e.target.closest('button');if(!b)return;
 if(b.dataset.go){if(page==='reflection')updateRecord({note:$('#reflection-note').value,next:$('#reflection-next')?.value||''});navigate(b.dataset.go);return;}
 if(b.dataset.age){model.age=b.dataset.age;save();navigate('height');return;}
 if(b.dataset.goal){model.goal=b.dataset.goal;save();navigate('barrier');return;}
 if(b.dataset.barrier){model.barrier=b.dataset.barrier;save();navigate('habits');return;}
 if(b.dataset.wheelValue){const w=$('#measure-wheel');w.scrollTo({top:Number(b.dataset.wheelIndex)*52,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});return;}
 if(b.dataset.suggest){$('#goal').value=b.dataset.suggest;$('#goal').setCustomValidity('');return;}
 if(b.dataset.habit){const id=b.dataset.habit;if(model.selected.includes(id))model.selected=model.selected.filter(h=>h!==id);else if(model.selected.length<5)model.selected.push(id);else{$('#pick-status').textContent='עד חמישה הרגלים. אפשר להסיר אחד כדי לבחור אחר.';return;}save();render();return;}
 if(b.dataset.check){ensureStart();const r=record(),id=b.dataset.check,checks=r.checks.includes(id)?r.checks.filter(h=>h!==id):[...r.checks,id];updateRecord({checks});const position=screen.scrollTop;render();screen.scrollTop=position;return;}
 if(b.dataset.day){viewDay=Number(b.dataset.day);page='today';render();screen.scrollTop=0;return;}
 if(b.dataset.mood){const note=$('#reflection-note').value;updateRecord({mood:Number(b.dataset.mood),note,next:$('#reflection-next')?.value||''});render();return;}
 const a=b.dataset.action;
 if(a==='save-measure'||a==='skip-measure'){const key=page;model[key]=a==='skip-measure'?'':$('#measure-wheel').getAttribute('aria-valuenow');save();navigate(key==='height'?'weight':'goal');return;}
 if(screens.some(s=>s[0]===a)){if(page==='reflection')updateRecord({note:$('#reflection-note').value,next:$('#reflection-next')?.value||''});navigate(a);return;}
 if(a==='install')modal('<h2>האתגר במסך הבית</h2><p>באייפון: פותחים ב־Safari, לוחצים על שיתוף ובוחרים ״הוסף למסך הבית״.</p><p>באנדרואיד: פותחים ב־Chrome ובתפריט בוחרים ״הוספה למסך הבית״.</p><p>בדמו הזה לא נשלחות התראות, גם לאחר ההוספה. אפשר לראות את נוסח התזכורות במסך היעדים.</p>');
 if(a==='about')modal('<h2>אתגר 21 יום עם איתי · המחשה</h2><p>כיוון למוצר מתוך השיחה עם איתי: אתגר אישי, הרגלים לבחירה ומעקב יומי פשוט.</p><p>הנתונים נשמרים רק בדפדפן הזה. אין חשבון משותף, סנכרון למאמן או התראות אמיתיות. יעדי הדוגמה והמשפטים היומיים הם הצעת תוכן, ולא הנחיות שאיתי אישר.</p><p>בתפריט שמתחת למסך אפשר להציג את יום 7 ואת יום 21. נתוני ההמחשה נפרדים מהאתגר האישי שלך.</p>');
 if(a==='close')$('#dialog').close();
 if(a==='reset')modal('<h2>להתחיל מחדש?</h2><p>הפעולה תמחק את המטרה והסימונים השמורים בדמו הזה בלבד.</p><button class="primary" data-action="confirm-reset">כן, לאפס את הדוגמה</button>');
 if(a==='confirm-reset'){model=fresh();demoDay=0;demoRecords={};viewDay=null;$('#demo-day').value='0';save();$('#dialog').close();navigate('welcome');}
 if(a==='share'){const s=stats(),r=record(),addition=$('#message').value;const text=`היי איתי, רציתי לשתף מהאתגר של 21 הימים.\nהמטרה שלי: ${model.goal||'לבנות שגרה שמתאימה לי'}\nיום ${shownDay()} · ${s.days} ימים עם עשייה · ${s.checks} סימונים.\n${r.note?'הסיכום שלי: '+r.note+'\n':''}${r.next?'לשבוע הבא: '+r.next+'\n':''}${model.keepHabit?'ההרגל להמשך: '+(active().find(h=>h.id===model.keepHabit)?.title||'')+'\n':''}${addition}${demoDay?'\n(סיכום מתוך המחשה)':''}`;window.open('https://wa.me/972559277324?text='+encodeURIComponent(text),'_blank','noopener');}
});
document.addEventListener('submit',e=>{
 e.preventDefault();
 if(e.target.id==='goal-form'){model.goal=$('#goal').value.trim();if(!model.goal){$('#goal').setCustomValidity('אפשר לבחור מטרה מהרשימה או לכתוב מטרה קצרה.');$('#goal').reportValidity();return;}save();navigate('barrier');}
 if(e.target.id==='custom-form'){const title=$('#custom').value.trim();if(!title)return;if(model.selected.length>=5){$('#pick-status').textContent='אפשר לבחור עד חמישה הרגלים. אפשר להסיר אחד כדי להוסיף הרגל אישי.';return;}const id='custom-'+Date.now();model.habits.push({id,title,hint:'הרגל אישי',target:title,time:'20:00',reminder:false});model.selected.push(id);save();render();}
 if(e.target.id==='rhythm-form'){const form=new FormData(e.target);for(const h of active()){h.target=String(form.get('target-'+h.id)).trim();h.time=String(form.get('time-'+h.id));h.reminder=form.has('reminder-'+h.id);}ensureStart();save();navigate('today');}
 if(e.target.id==='reflection-form'){updateRecord({note:$('#reflection-note').value.trim(),next:$('#reflection-next')?.value.trim()||'',closed:true});$('#reflection-status').textContent=demoDay?'הסיכום נשמר בהמחשה.':storageWorks?'הסיכום שמור במכשיר שלך.':'נשמר בעמוד הפתוח בלבד. השמירה במכשיר אינה זמינה.';}
});
document.addEventListener('input',e=>{if(e.target.id==='goal')e.target.setCustomValidity('');if(e.target.closest('#rhythm-form')){for(const h of active()){const box=screen.querySelector(`[data-reminder-preview="${h.id}"]`);box.hidden=!screen.querySelector(`[name="reminder-${h.id}"]`).checked;box.querySelector('[data-preview-time]').textContent=screen.querySelector(`[name="time-${h.id}"]`).value;box.querySelector('[data-preview-text]').textContent=reminderText({...h,target:screen.querySelector(`[name="target-${h.id}"]`).value});}}});
document.addEventListener('change',e=>{if(e.target.id==='keep-habit'){model.keepHabit=e.target.value;save();$('#keep-status').textContent=storageWorks?'הבחירה שמורה במכשיר הזה.':'הבחירה נשמרה בעמוד הפתוח בלבד.';}});
$('#demo-day').addEventListener('change',e=>{demoDay=Number(e.target.value);viewDay=null;navigate(demoDay===21?'summary':demoDay===7?'journey':'today');});

function scene(kind,compact=false){
 const visuals={
 age:'<path d="M65 119h46V99h45V76h45V51h48" fill="none" stroke="#d2b37f" stroke-width="18" stroke-linejoin="round"/><circle cx="236" cy="31" r="15" fill="#e8ce9d"/><path d="m110 110 39-24 33 8 35-45" fill="none" stroke="#334a5c" stroke-width="3" stroke-linecap="round"/>',
 height:'<rect x="175" y="24" width="33" height="111" rx="9" fill="#d9bd8c"/><path d="M179 39h14m-14 15h8m-8 15h14m-14 15h8m-8 15h14m-14 15h8" stroke="#9d8054" stroke-width="2"/><path d="M137 132V55m0 33c-23-1-27-17-23-26 19 0 25 10 23 26Zm0 19c24-1 29-17 24-26-18 0-26 10-24 26Z" fill="#9ead95" stroke="#6b8269" stroke-width="2"/><path d="M118 133h39" stroke="#334a5c" stroke-width="4" stroke-linecap="round"/>',
 weight:'<rect x="108" y="41" width="117" height="96" rx="25" fill="#344b5c"/><rect x="118" y="47" width="97" height="75" rx="20" fill="#e1e8db"/><path d="M141 78a26 26 0 0 1 51 0" fill="#faf5e9" stroke="#b9c6b0" stroke-width="2"/><path d="m166 80 12-17" stroke="#b58e57" stroke-width="3" stroke-linecap="round"/><circle cx="166" cy="80" r="4" fill="#344b5c"/><path d="M143 100v9m45-9v9" stroke="#b6c5ae" stroke-width="4" stroke-linecap="round"/>',
 goal:'<circle cx="170" cy="79" r="48" fill="#e0e8da"/><circle cx="170" cy="79" r="31" fill="#f9f4e8"/><circle cx="170" cy="79" r="15" fill="#d4b784"/><path d="m172 77 52-48m-4-4 2 19 19 2" stroke="#334b5b" stroke-width="4" fill="none" stroke-linecap="round"/>',
 barrier:'<path d="M96 136c84 0 96-19 61-49s-4-47 80-47" stroke="#d8c198" stroke-width="17" fill="none" stroke-linecap="round"/><path d="m103 74 27-26 24 26Z" fill="#9cac94"/><circle cx="236" cy="39" r="10" fill="#344b5c"/><path d="m232 39 3 3 6-7" stroke="#f7eedb" fill="none" stroke-width="2"/>',
 habits:'<rect x="115" y="27" width="100" height="115" rx="16" fill="#fff9eb" stroke="#c4cfbd" stroke-width="2"/><rect x="138" y="20" width="54" height="17" rx="8" fill="#d6b982"/><path d="m132 61 5 5 9-10m-14 32 5 5 9-10m-14 32 5 5 9-10" stroke="#668067" stroke-width="3" fill="none"/><path d="M158 61h35m-35 27h35m-35 27h24" stroke="#bac8b1" stroke-width="4" stroke-linecap="round"/>',
 rhythm:'<circle cx="167" cy="80" r="48" fill="#e2e8dc" stroke="#a6b69b" stroke-width="2"/><circle cx="167" cy="80" r="38" fill="#faf5e8"/><path d="M167 52v29l23 13" stroke="#344b5c" stroke-width="4" fill="none" stroke-linecap="round"/><circle cx="167" cy="80" r="5" fill="#d6b982"/><path d="m128 36-11 13m89-13 11 13" stroke="#d6b982" stroke-width="9" stroke-linecap="round"/>',
 reflection:'<path d="M100 45q33-11 65 8 34-19 68-8v80q-33-11-68 8-33-19-65-8Z" fill="#fff9ed" stroke="#b3c2a9" stroke-width="2"/><path d="M165 55v74m-49-63 31 7m-31 9 31 7m36-16 31-7m-31 23 31-7" stroke="#c2cdb9" stroke-width="3" stroke-linecap="round"/><path d="m202 43 18-20" stroke="#d2b37f" stroke-width="7" stroke-linecap="round"/>',
 contact:'<rect x="92" y="35" width="108" height="65" rx="22" fill="#344b5c"/><path d="m112 94-6 19 30-16" fill="#344b5c"/><rect x="162" y="77" width="86" height="54" rx="19" fill="#d6b982"/><path d="m228 127 8 16-28-13" fill="#d6b982"/><g fill="#faf4e8"><circle cx="121" cy="67" r="4"/><circle cx="146" cy="67" r="4"/><circle cx="171" cy="67" r="4"/></g>'
 };
 return `<div class="scene ${compact?'scene-compact':''}" aria-hidden="true"><svg viewBox="0 0 340 160"><ellipse cx="170" cy="92" rx="123" ry="62" fill="#eeeadd"/><circle cx="254" cy="35" r="13" fill="#e9dfc5"/>${visuals[kind]||visuals.goal}<path d="M65 139h204" stroke="#d6dece" stroke-width="2" stroke-linecap="round"/></svg></div>`;
}
function measurementWheel(key,min,max,step,fallback,unit){
 const value=model[key]!==''&&model[key]!=null?Math.min(max,Math.max(min,Number(model[key]))):fallback;
 const values=Array.from({length:Math.round((max-min)/step)+1},(_,i)=>min+i*step);
 return `<div class="measurement"><div class="measurement-value"><output id="measurement-value">${value}</output><span>${unit}</span></div><div class="wheel-shell"><div class="wheel-highlight" aria-hidden="true"></div><div id="measure-wheel" class="measure-wheel" role="spinbutton" tabindex="0" aria-label="${key==='height'?'גובה בסנטימטרים':'משקל בקילוגרמים'}" aria-valuemin="${min}" aria-valuemax="${max}" aria-valuenow="${value}" data-min="${min}" data-step="${step}" data-unit="${unit}">${values.map((v,i)=>`<div class="wheel-tick" aria-hidden="true" data-wheel-value="${v}" data-wheel-index="${i}"><span class="tick-mark"></span><span>${Number.isInteger(v)?v:v.toFixed(1)}</span><span class="tick-mark"></span></div>`).join('')}</div></div><p class="tiny center">אפשר גם להשתמש בחיצי המקלדת</p></div>`;
}
function initWheel(){
 const wheel=$('#measure-wheel'),min=Number(wheel.dataset.min),step=Number(wheel.dataset.step),initial=Number(wheel.getAttribute('aria-valuenow'));
 let raf=0;
 const update=()=>{const index=Math.max(0,Math.min(wheel.children.length-1,Math.round(wheel.scrollTop/52))),value=min+index*step;wheel.setAttribute('aria-valuenow',value);wheel.setAttribute('aria-valuetext',value+' '+wheel.dataset.unit);$('#measurement-value').textContent=value;for(let i=0;i<wheel.children.length;i++)wheel.children[i].classList.toggle('selected',i===index);};
 wheel.scrollTop=Math.round((initial-min)/step)*52;update();
 wheel.addEventListener('scroll',()=>{cancelAnimationFrame(raf);raf=requestAnimationFrame(update);},{passive:true});
 wheel.addEventListener('keydown',e=>{let value=Number(wheel.getAttribute('aria-valuenow'));if(e.key==='ArrowDown')value+=step;else if(e.key==='ArrowUp')value-=step;else if(e.key==='Home')value=min;else if(e.key==='End')value=Number(wheel.getAttribute('aria-valuemax'));else return;e.preventDefault();wheel.scrollTop=Math.max(0,Math.min(wheel.children.length-1,Math.round((value-min)/step)))*52;update();});
 wheel.addEventListener('click',e=>{const tick=e.target.closest('[data-wheel-index]');if(tick)wheel.scrollTo({top:Number(tick.dataset.wheelIndex)*52,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});});
}
render();
