const $=s=>document.querySelector(s);
const escapeHTML=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const KEY='maklef-21-demo-v1';
const icons={nutrition:'<path d="M4 3v7m3-7v7m-6-7v7h6M4 10v11M15 3v18m0-18c6 2 6 9 0 9"/>',move:'<path d="m3 16 4-4 4 3 4-8 6 3M7 12l-3-2m7 5-3 6m7-14 1-4"/><circle cx="17" cy="3" r="1.5"/>',water:'<path d="M12 3S5 11 5 15a7 7 0 0 0 14 0c0-4-7-12-7-12Z"/><path d="M9 15a3 3 0 0 0 3 3"/>',read:'<path d="M12 6c-3-3-7-3-9-2v15c3-1 6-1 9 1 3-2 6-2 9-1V4c-2-1-6-1-9 2Zm0 0v14"/>',write:'<path d="m4 16 12-12 4 4L8 20H4v-4Zm9-9 4 4M4 22h16"/>',sleep:'<path d="M20 15A9 9 0 0 1 9 4a9 9 0 1 0 11 11Z"/>',custom:'<path d="m12 3 2.7 5.5 6.1.9-4.4 4.3 1 6.1L12 17l-5.4 2.8 1-6.1-4.4-4.3 6.1-.9Z"/>'};
const icon=id=>`<span class="icon" aria-hidden="true"><svg viewBox="0 0 24 24">${icons[id]||icons.custom}</svg></span>`;
const catalog=[{id:'move',title:'אימון',hint:'הליכה, ריצה או כוח',target:'30 דקות הליכה',time:'18:00'},{id:'nutrition',title:'תזונה',hint:'לפי התוכנית האישית',target:'להכין ארוחה אחת לפי התוכנית שלי',time:'19:00'},{id:'water',title:'מים',hint:'יעד שתייה אישי לאורך היום',target:'למלא בקבוק מים אחד לקראת היום',time:'12:00'},{id:'read',title:'קריאה',hint:'כמה עמודים ביום',target:'10 עמודים',time:'22:00'},{id:'write',title:'כתיבה',hint:'כמה שורות על היום',target:'3 שורות על היום',time:'21:00'},{id:'sleep',title:'שינה',hint:'ללכת לישון בשעה קבועה',target:'במיטה עד 22:30',time:'22:00'}];
const fresh=()=>({name:'',goal:'',barrier:'',keepHabit:'',height:'',weight:'',selected:['move','read'],habits:catalog.map(h=>({...h,reminder:false})),start:null,records:{}});
let model=fresh(),storageWorks=true;
try{const saved=JSON.parse(localStorage.getItem(KEY)||'null');if(saved&&Array.isArray(saved.habits)&&Array.isArray(saved.selected)&&saved.records)model=saved;}catch{storageWorks=false;}
// Refresh catalog labels without overwriting personal targets or recorded progress.
for(const h of catalog){const saved=model.habits.find(x=>x.id===h.id);if(saved){saved.title=h.title;saved.hint=h.hint;}else model.habits.push({...h,reminder:false});}
let page=model.start?'today':'welcome',demoDay=0,demoRecords={},viewDay=null,previousPage=page;
const calendarDate=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
function dateNumber(date){const [y,m,d]=date.split('-').map(Number);return Date.UTC(y,m-1,d)/86400000;}
function realDay(){return model.start?Math.max(1,Math.min(21,Math.floor(dateNumber(calendarDate())-dateNumber(model.start))+1)):1;}
const currentDay=()=>demoDay||realDay();
const shownDay=()=>viewDay||currentDay();
const records=()=>demoDay?demoRecords:model.records;
const active=()=>model.habits.filter(h=>model.selected.includes(h.id));
const record=(day=shownDay())=>records()[day]||{checks:[],mood:null,note:'',closed:false};
function save(){try{localStorage.setItem(KEY,JSON.stringify(model));storageWorks=true;}catch{storageWorks=false;}}
function updateRecord(change){const d=shownDay();records()[d]={...record(d),...change};if(!demoDay)save();}
const countDone=day=>active().filter(h=>record(day).checks.includes(h.id)).length;
const stats=()=>({checks:Object.values(records()).reduce((n,r)=>n+active().filter(h=>r.checks.includes(h.id)).length,0),days:Object.values(records()).filter(r=>active().some(h=>r.checks.includes(h.id))).length,closed:Object.values(records()).filter(r=>r.closed).length});
function streak(){let d=currentDay(),n=0;if(!countDone(d))d--;while(d>0&&countDone(d)>0){n++;d--;}return n;}
const reminderText=h=>`${h.title}. ${h.target}. אחר כך מסמנים.`;
const screens=[['welcome','התחלה קטנה','21 יום.<br>בונים משמעת.','בוחרים הרגלים. עושים. מסמנים. כל יום.'],['goal','מטרה אישית','מה המטרה שלך<br>באתגר?','מטרה במילים שלך, בלי שאלון ארוך.'],['habits','ההרגלים שלי','לא חייבים חמישה.<br>אפשר להתחיל מאחד.','בוחרים הרגלים שמתאימים לאדם, לא להפך.'],['rhythm','הקצב שלי','יעד ברור.<br>שעה קבועה.','לכל הרגל יעד ברור ושעה לבחירתך.'],['today','היום שלי','פחות לחשוב.<br>יותר פשוט לעשות.','היעדים מול העיניים. מסמנים אחרי שעושים.'],['journey','21 הדלתות','כל יום נפתחת<br>עוד דלת.','רואים את הדרך שעברת ואת מה שעוד לפניך.'],['reflection','סגירת יום','מה עבד?<br>מה משנים?','משוב קצר במקום עוד טופס.'],['summary','ממשיכים מכאן','21 יום הם התחלה.<br>מה לוקחים הלאה?','סיכום אישי ואפשרות להמשיך לליווי עם איתי.'],['contact','בקשר עם איתי','מדברים<br>עם איתי.','אפשר לפתוח שיחה עם סיכום אישי, ולשלוח כשמוכנים.']];
const screen=$('#screen');
const primary=(label,action)=>`<button class="primary" type="button" data-action="${action}">${label}<span aria-hidden="true">←</span></button>`;
const secondary=(label,action)=>`<button class="secondary" type="button" data-action="${action}">${label}</button>`;
const heading=(text,eyebrow='')=>`${eyebrow?`<div class="eyebrow">${eyebrow}</div>`:''}<h2 tabindex="-1">${text}</h2>`;
const actions=(...content)=>`<div class="actions">${content.join('')}</div>`;
const setupStep=n=>`<div class="step"><button class="back" data-go="${['welcome','goal','habits'][n-1]}">→ חזרה</button><span>${n} מתוך 3 · בונים את האתגר שלך</span></div><div class="progress"><span style="width:${n/3*100}%"></span></div>`;
const quote=['לא צריך להרגיש מוכנים. צריך להתחיל.', 'משמעת זה לעשות גם כשאין הרבה חשק.', 'יום 3. ממשיכים עם מה שקבענו.', 'קטן ועקבי מנצח גדול ופעם אחת.', 'היעד ברור. השעה ביומן. עכשיו עושים.', 'מסמנים מה שעשינו. רואים מה צריך לשפר.', 'שבוע אחד בפנים. עוד שניים.', 'לא מחכים למוטיבציה. חוזרים לתוכנית.', 'גם יום חלקי הוא יום שעשינו בו משהו.', 'מה עזר עד עכשיו? לוקחים את זה גם להיום.', 'חצי דרך. זמן לראות מה עובד ומה צריך לדייק.', 'פספסת אתמול? היום אפשר לחזור.', 'לא חייבים לחכות ליום פנוי. קובעים זמן ביומן.', 'שבועיים בפנים. מה כבר קל יותר לעשות?', 'יום קשה? מתאימים את היעד למציאות, יחד עם איתי.', 'גם מנוחה לפי התוכנית היא חלק ממשמעת.', 'הרגלים מתרגלים גם בימים רגילים.', 'קודם עושים. אחר כך מסמנים.', 'קו הסיום קרוב. ממשיכים לפי התוכנית.', 'מחר מסכמים. היום עושים את מה שקבענו.', 'יום 21. מה ממשיכים לעשות גם מחר?'];
function art(ending=false){return `<svg class="art ${ending?'ending-art':''}" viewBox="0 0 350 205" role="img" aria-label="איור של שביל מתפתל בין גבעות ושער פתוח"><defs><linearGradient id="sky" x2="0" y2="1"><stop stop-color="#ecebe0"/><stop offset="1" stop-color="#f6f2e8"/></linearGradient><linearGradient id="door" x2="1" y2="1"><stop stop-color="#d1b588"/><stop offset="1" stop-color="#ece0c4"/></linearGradient></defs><rect x="4" y="4" width="342" height="195" rx="90" fill="url(#sky)"/><circle cx="251" cy="49" r="21" fill="#ddbe89"/><path d="M6 160Q79 70 171 142T344 111V179Q344 199 325 199H25Q5 199 6 180Z" fill="#dce3d6"/><path d="M6 168Q105 118 193 160T344 147V184Q344 199 328 199H23Q6 199 6 184Z" fill="#c3cfbf"/><path d="M151 199Q223 171 191 153T172 121" stroke="#f7f0df" stroke-width="23" fill="none"/><path d="M151 199Q223 171 191 153T172 121" stroke="#cfbda0" stroke-width="1" stroke-dasharray="3 8" fill="none"/><path d="M148 126V83a24 24 0 0 1 48 0v43Z" fill="#25394b"/><path d="M156 126V84a16 16 0 0 1 32 0v42Z" fill="#f8f2dd"/><path d="M156 126V84q0-17 17-16v48Z" fill="url(#door)"/><circle cx="167" cy="98" r="1.5" fill="#8c744f"/><path d="M59 140v-28m0 11-9-8m9 14 9-8M293 151v-26m0 11 8-9" stroke="#8c9e86" stroke-width="2" fill="none"/><g fill="#fff9e9"><circle cx="224" cy="92" r="2"/><circle cx="105" cy="72" r="2"/><circle cx="276" cy="101" r="1.5"/></g></svg>`;}
function navigate(to){const keepDay=(to==='reflection'&&page==='today')||(to==='contact'&&['today','reflection'].includes(page));previousPage=page;page=to;if(!keepDay)viewDay=null;render();screen.scrollTop=0;screen.querySelector('h2')?.focus({preventScroll:true});}
function ensureStart(){if(!model.start){model.start=calendarDate();save();}}
function render(){
 if(!active().length&&['rhythm','today','journey','reflection','summary','contact'].includes(page))page='habits';
 const meta=screens.find(s=>s[0]===page),index=screens.indexOf(meta);
 $('#stage-label').textContent=String(index+1).padStart(2,'0')+' / '+meta[1];$('#stage-title').innerHTML=meta[2];$('#stage-copy').textContent=meta[3];
 $('#preview').innerHTML=screens.map(([id,label],i)=>`<button data-go="${id}" ${id===page?'aria-current="step"':''} aria-label="מסך ${i+1}: ${label}">${String(i+1).padStart(2,'0')}</button>`).join('');
 const preview=$('#preview'),selectedPreview=preview.querySelector('[aria-current]');if(selectedPreview)preview.scrollLeft=selectedPreview.offsetLeft-preview.offsetLeft-preview.clientWidth/2+20;
 const tabItems=[['today','היום שלי'],['journey','הדרך שלי'],['reflection','סוגרים יום'],['rhythm','ההרגלים שלי']];
 const showTabs=model.start&&['today','journey','reflection','rhythm','summary','contact'].includes(page);
 $('#tabs').hidden=!showTabs;$('#tabs').innerHTML=tabItems.map(([id,label])=>`<button data-go="${id}" class="${id===page?'active':''}" ${id===page?'aria-current="page"':''}>${label}</button>`).join('');
 if(page==='welcome')screen.innerHTML=`<div class="center welcome">${art()}${heading('21 יום של משמעת','עם איתי מקלף')}<p class="brand-line">משמעת חזקה,<br>בלי יותר מדי מוטיבציה.</p><p class="intro-sub">בוחרים הרגלים. עושים. מסמנים. כל יום.</p></div>${actions(primary(model.start?'חוזרים להיום':'מתחילים',model.start?'today':'goal'),'<button class="install-link" data-action="install">הוספת האתגר למסך הבית</button>')}`;
 if(page==='goal')screen.innerHTML=setupStep(1)+heading('לפני שמתחילים')+`<form id="goal-form" class="grow"><label class="field">איך קוראים לך?<input id="name" autocomplete="given-name" maxlength="35" placeholder="השם שלך · לא חובה" value="${escapeHTML(model.name)}"></label><details class="measurements"><summary>גובה ומשקל · לא חובה</summary><div class="two"><label class="field">גובה בס״מ<input id="height" type="number" inputmode="decimal" min="100" max="230" value="${escapeHTML(model.height)}"></label><label class="field">משקל בק״ג<input id="weight" type="number" inputmode="decimal" min="30" max="300" step="0.1" value="${escapeHTML(model.weight)}"></label></div></details><label class="field">בעוד 21 יום, אני רוצה…<textarea id="goal" maxlength="180" required placeholder="למשל: להתמיד באימונים שקבעתי לעצמי">${escapeHTML(model.goal)}</textarea></label><div class="suggestions">${['להתמיד באימונים','להתקדם ליעד המשקל שלי','לישון בזמן','יותר אנרגיה'].map(x=>`<button type="button" data-suggest="${x}">${x}</button>`).join('')}</div><fieldset class="barrier"><legend>מה בדרך כלל עוצר אותך באמצע?</legend><div class="suggestions">${['עומס','אין זמן','נגמר החשק','יום רע שהופך לשבוע'].map(x=>`<label class="barrier-option"><input type="radio" name="barrier" value="${x}" ${model.barrier===x?'checked':''}><span>${x}</span></label>`).join('')}</div><span class="tiny">לא חובה לבחור.</span></fieldset><div class="actions"><button class="primary" type="submit">לבחירת ההרגלים <span>←</span></button></div></form>`;
 if(page==='habits')screen.innerHTML=setupStep(2)+heading('על מה עובדים<br>21 יום?')+`<p class="muted">עד 5 הרגלים שסיכמת עם איתי.<br>גם אחד מספיק.</p><div class="pick-list">${model.habits.map(h=>`<button class="pick" data-habit="${h.id}" aria-pressed="${model.selected.includes(h.id)}">${icon(h.id)}<span class="pick-copy"><strong>${escapeHTML(h.title)}</strong><small>${escapeHTML(h.hint||'הרגל אישי שלך')}</small></span><span class="check" aria-hidden="true">${model.selected.includes(h.id)?'✓':''}</span></button>`).join('')}</div><form id="custom-form" class="custom-input"><input id="custom" aria-label="הרגל משלי" maxlength="45" placeholder="או הרגל משלי…"><button type="submit" aria-label="הוספת הרגל אישי">＋</button></form><div class="status-message" id="pick-status" role="status">${model.selected.length} מתוך 5 נבחרו</div>${actions(`<button class="primary" data-action="rhythm" ${model.selected.length?'':'disabled'}>מגדירים יעדים <span>←</span></button>`)}`;
 if(page==='rhythm')screen.innerHTML=(model.start?'<div class="step"><button class="back" data-go="today">→ חזרה ליום שלי</button><button class="text-button" data-go="habits">שינוי הרגלים</button></div>':setupStep(3))+heading('יעד ותזכורת')+`<p class="muted">לכל הרגל יעד שאפשר לסמן כבוצע.<br>הדוגמאות ניתנות לעריכה לפי התוכנית האישית.</p><form class="grow" id="rhythm-form">${active().map(h=>`<div class="habit-setting"><div class="row">${icon(h.id)}<h3>${escapeHTML(h.title)}</h3></div><label class="field">מה נחשב ״עשיתי״?<input name="target-${h.id}" required maxlength="90" value="${escapeHTML(h.target)}"></label><div class="reminder-row"><label><input type="checkbox" name="reminder-${h.id}" ${h.reminder?'checked':''}>תזכורת</label><input type="time" name="time-${h.id}" aria-label="שעת תזכורת עבור ${escapeHTML(h.title)}" value="${h.time}" required></div><div class="reminder-preview" data-reminder-preview="${h.id}" ${h.reminder?'':'hidden'}><span>תצוגת תזכורת · <b data-preview-time>${h.time}</b></span><strong data-preview-text>${escapeHTML(reminderText(h))}</strong></div></div>`).join('')}<div class="reminder-preview"><span>סיכום היום · תזכורת לדוגמה · 21:30</span><strong>עוד לא סימנת את היום? זה הזמן לבדוק מה בוצע.</strong></div><div class="notification-note">כך ייראו התזכורות. בדמו לא נשלחות התראות למכשיר.</div><div class="actions"><button class="primary" type="submit">${model.start?'שומרים וחוזרים ליום שלי':'מתחילים את יום 1'} <span>←</span></button></div></form>`;
 if(page==='today'){
 const d=shownDay(),done=countDone(d),all=done===active().length,r=record(d);
 screen.innerHTML=`<div class="row"><span class="eyebrow" style="margin:0">${model.name?'היי '+escapeHTML(model.name):'האתגר שלי'}</span><button class="text-button" data-go="contact">בקשר עם איתי</button></div><div class="day-hero"><div>${heading(`יום ${d} מתוך 21`)}<p>המטרה שלי: ${escapeHTML(model.goal||'לבנות שגרה שמתאימה לי')}</p></div><div class="day-ring"><div><b>${d}</b><small>מתוך 21 ימים</small></div></div></div><div class="quote daily-quote">${quote[d-1]}</div><div class="row"><span class="section-heading">ההרגלים שלי להיום</span><span class="section-count">היום: ${done} מתוך ${active().length}</span></div><div class="daily-list">${active().map(h=>`<button class="daily-task" data-check="${h.id}" aria-pressed="${r.checks.includes(h.id)}" aria-label="${escapeHTML(h.title)}: ${escapeHTML(h.target)}">${icon(h.id)}<span class="content"><strong>${escapeHTML(h.target)}</strong><small>${h.reminder?'תזכורת לדוגמה · '+h.time:escapeHTML(h.title)}</small></span><span class="circle" aria-hidden="true">${r.checks.includes(h.id)?'✓':''}</span></button>`).join('')}</div>${all?`<div class="reflection-stamp" role="status">${d===21?'כל היעדים של היום סומנו. לסיכום האתגר!':'היום סגור. נתראה מחר.'}</div>`:done>0?`<div class="partial-day" role="status">${done} מתוך ${active().length}. גם זה יום שנספר.</div>`:''}${actions(primary(r.closed?'לסיכום ששמרתי':'סיכום היום','reflection'))}`;
 }
 if(page==='journey'){
 const s=stats(),day=currentDay();screen.innerHTML=heading('כל יום נפתחת<br>עוד דלת.','הדרך שלי')+`<p class="muted">גם יום שלא הספקת בו הכול נשאר חלק מהדרך.</p><div class="journey-grid">${Array.from({length:21},(_,i)=>{const d=i+1,r=record(d),finished=r.checks.length>0&&countDone(d)===active().length;return `<button class="door ${d===day?'today':''} ${d<day?'open':''} ${finished?'done':''}" data-day="${d}" ${d>day?'disabled':''} aria-label="יום ${d}${d>day?', עדיין לא נפתח':finished?', כל ההרגלים הושלמו':d===day?', היום':''}"><span>${String(d).padStart(2,'0')}</span><small>${finished?'✓':d===day?'היום':d>day?'·':''}</small></button>`;}).join('')}</div><div class="legend"><span>היום</span><span>כל היעדים הושלמו</span><span>בהמשך</span></div><div class="stats"><div class="stat"><b>${s.days}</b><span>ימים עם עשייה</span></div><div class="stat"><b>${s.checks}</b><span>הרגלים שסומנו</span></div><div class="stat"><b>${streak()}</b><span>ימים ברצף</span></div></div><p class="tiny">רצף = ימים עם לפחות הרגל אחד שסומן. היום נשאר פתוח עד חצות.</p><div class="panel"><h3>המטרה שלי</h3><p>${escapeHTML(model.goal||'לבנות שגרה שמתאימה לי')}</p></div>${actions(primary(day===21?'לסיכום הדרך':'חזרה להיום',day===21?'summary':'today'))}`;
 }
 if(page==='reflection'){
 const d=shownDay(),weekly=d===7||d===14,r=record(d);screen.innerHTML=`<div class="step"><button class="back" data-go="today">→ חזרה</button><span>יום ${d} מתוך 21</span></div>`+heading(weekly?(d===7?'שבוע אחד בפנים.<br>איך הולך?':'שבועיים בפנים.<br>איך הולך?'):'איך הלך היום?',weekly?'סיכום שבועי':'סיכום היום')+`<p class="muted">${weekly?'מה שומרים, ומה משפרים לשבוע הבא?':'מה עבד, ומה אפשר לעשות אחרת מחר?'}</p><div class="moods">${['היה מאתגר','היה בסדר','היה טוב'].map((m,n)=>`<button data-mood="${n}" aria-pressed="${r.mood===n}">${m}</button>`).join('')}</div><form id="reflection-form" class="grow"><label class="field">${weekly?'מה עבד השבוע?':'מה חשוב לי לזכור מהיום?'}<textarea id="reflection-note" maxlength="600" placeholder="אפשר גם משפט אחד…">${escapeHTML(r.note)}</textarea></label>${weekly?`<label class="field">מה משנים לשבוע הבא?<textarea id="reflection-next" maxlength="400" placeholder="שינוי אחד שאפשר לנסות…">${escapeHTML(r.next||'')}</textarea></label>`:''}<p class="tiny">הסיכום אישי. איתי רואה אותו רק אם שולחים.</p><div class="actions"><button type="submit" class="primary">שומרים סיכום <span>✓</span></button>${weekly?secondary('משתפים את איתי','contact'):''}</div><p id="reflection-status" class="toast" role="status">${r.closed?'הסיכום שלך שמור במכשיר הזה.':''}</p></form>`;
 }
 if(page==='summary'){
 const s=stats();screen.innerHTML=`<div class="center">${art(true)}${heading(currentDay()===21?(s.days===21?'21 יום.<br>עשית את זה.':'21 יום.<br>מה לוקחים הלאה?'):'האתגר שלך, עד עכשיו.')}<p class="muted">הנה מה שסימנת במהלך האתגר.</p></div><div class="stats"><div class="stat"><b>${s.days}</b><span>ימים עם עשייה</span></div><div class="stat"><b>${s.checks}</b><span>הרגלים שסומנו</span></div><div class="stat"><b>${active().length}</b><span>הרגלים שבחרת</span></div></div><div class="summary-list">${active().map(h=>`<div class="summary-item"><span>${escapeHTML(h.title)}</span><b>${Object.values(records()).filter(r=>r.checks.includes(h.id)).length} סימונים</b></div>`).join('')}</div><label class="field">עם איזה הרגל ממשיכים מכאן?<select id="keep-habit"><option value="">בוחרים הרגל</option>${active().map(h=>`<option value="${h.id}" ${model.keepHabit===h.id?'selected':''}>${escapeHTML(h.title)}</option>`).join('')}</select></label><p id="keep-status" class="tiny" role="status"></p><p class="journey-note">${demoDay?'זו תצוגת סוף האתגר. המספרים משקפים רק סימונים שבוצעו בהמחשה.':'הסיכום מבוסס על הסימונים שלך במכשיר הזה.'}</p>${actions(primary('להמשיך עם איתי בליווי אישי','contact'),secondary('לצפייה באתגר שלי','journey'))}`;
 }
 if(page==='contact'){
 const s=stats();screen.innerHTML=`<div class="step"><button class="back" data-go="today">→ חזרה</button><span>עם איתי</span></div>`+heading('מדברים עם איתי')+`<p class="muted">יש שאלה או משהו שחשוב לשתף?</p><div class="panel"><span class="tag">הסיכום שלי</span><h3 style="margin-top:14px">${escapeHTML(model.goal||'אתגר 21 יום')}</h3><p>יום ${shownDay()} · ${s.days} ימים עם עשייה · ${s.checks} סימונים</p></div><label class="field">ההודעה שלי לאיתי:<textarea id="message" maxlength="500" placeholder="היי איתי, רציתי לשתף…"></textarea></label><p class="tiny">ההודעה תיפתח בוואטסאפ לעריכה. שולחים רק כשמוכנים.</p>${actions(primary('ממשיכים לוואטסאפ','share'))}`;
 }
 if(demoDay&&['today','journey','reflection','summary','contact'].includes(page))screen.insertAdjacentHTML('afterbegin',`<div class="demo-state">מציגים יום ${demoDay} להמחשה · הנתונים נפרדים מהאתגר שלך</div>`);
 if(!storageWorks)screen.insertAdjacentHTML('beforeend','<p class="toast" role="status">השמירה במכשיר אינה זמינה בדפדפן הזה. השינויים יישארו רק כל עוד העמוד פתוח.</p>');
}
function modal(html){$('#dialog-content').innerHTML=html;$('#dialog').showModal();}
document.addEventListener('click',e=>{
 const b=e.target.closest('button');if(!b)return;
 if(b.dataset.go){if(page==='reflection')updateRecord({note:$('#reflection-note').value,next:$('#reflection-next')?.value||''});navigate(b.dataset.go);return;}
 if(b.dataset.suggest){$('#goal').value=b.dataset.suggest;$('#goal').setCustomValidity('');return;}
 if(b.dataset.habit){const id=b.dataset.habit;if(model.selected.includes(id))model.selected=model.selected.filter(h=>h!==id);else if(model.selected.length<5)model.selected.push(id);else{$('#pick-status').textContent='עד חמישה הרגלים. אפשר להסיר אחד כדי לבחור אחר.';return;}save();render();return;}
 if(b.dataset.check){ensureStart();const r=record(),id=b.dataset.check,checks=r.checks.includes(id)?r.checks.filter(h=>h!==id):[...r.checks,id];updateRecord({checks});const position=screen.scrollTop;render();screen.scrollTop=position;return;}
 if(b.dataset.day){viewDay=Number(b.dataset.day);page='today';render();screen.scrollTop=0;return;}
 if(b.dataset.mood){const note=$('#reflection-note').value;updateRecord({mood:Number(b.dataset.mood),note,next:$('#reflection-next')?.value||''});render();return;}
 const a=b.dataset.action;
 if(screens.some(s=>s[0]===a)){if(page==='reflection')updateRecord({note:$('#reflection-note').value,next:$('#reflection-next')?.value||''});navigate(a);return;}
 if(a==='install')modal('<h2>האתגר במסך הבית</h2><p>באייפון: פותחים ב־Safari, לוחצים על שיתוף ובוחרים ״הוסף למסך הבית״.</p><p>באנדרואיד: פותחים ב־Chrome ובתפריט בוחרים ״הוספה למסך הבית״.</p><p>בדמו הזה לא נשלחות התראות, גם לאחר ההוספה. אפשר לראות את נוסח התזכורות במסך היעדים.</p>');
 if(a==='about')modal('<h2>21 עם איתי · המחשה</h2><p>כיוון למוצר מתוך השיחה עם איתי: אתגר אישי, הרגלים לבחירה ומעקב יומי פשוט.</p><p>הנתונים נשמרים רק בדפדפן הזה. אין חשבון משותף, סנכרון למאמן או התראות אמיתיות. יעדי הדוגמה והמשפטים היומיים הם הצעת תוכן, ולא הנחיות שאיתי אישר.</p><p>בתפריט שמתחת למסך אפשר להציג את יום 7 ואת יום 21. נתוני ההמחשה נפרדים מהאתגר האישי שלך.</p>');
 if(a==='close')$('#dialog').close();
 if(a==='reset')modal('<h2>להתחיל מחדש?</h2><p>הפעולה תמחק את המטרה והסימונים השמורים בדמו הזה בלבד.</p><button class="primary" data-action="confirm-reset">כן, לאפס את הדוגמה</button>');
 if(a==='confirm-reset'){model=fresh();demoDay=0;demoRecords={};viewDay=null;$('#demo-day').value='0';save();$('#dialog').close();navigate('welcome');}
 if(a==='share'){const s=stats(),r=record(),addition=$('#message').value;const text=`היי איתי, רציתי לשתף מהאתגר של 21 הימים.\nהמטרה שלי: ${model.goal||'לבנות שגרה שמתאימה לי'}\nיום ${shownDay()} · ${s.days} ימים עם עשייה · ${s.checks} סימונים.\n${r.note?'הסיכום שלי: '+r.note+'\n':''}${r.next?'לשבוע הבא: '+r.next+'\n':''}${model.keepHabit?'ההרגל להמשך: '+(active().find(h=>h.id===model.keepHabit)?.title||'')+'\n':''}${addition}${demoDay?'\n(סיכום מתוך המחשה)':''}`;window.open('https://wa.me/972559277324?text='+encodeURIComponent(text),'_blank','noopener');}
});
document.addEventListener('submit',e=>{
 e.preventDefault();
 if(e.target.id==='goal-form'){model.name=$('#name').value.trim();model.goal=$('#goal').value.trim();if(!model.goal){$('#goal').setCustomValidity('אפשר לכתוב מטרה קצרה או לבחור הצעה.');$('#goal').reportValidity();return;}model.barrier=document.querySelector('input[name=barrier]:checked')?.value||'';model.height=$('#height').value;model.weight=$('#weight').value;save();navigate('habits');}
 if(e.target.id==='custom-form'){const title=$('#custom').value.trim();if(!title)return;if(model.selected.length>=5){$('#pick-status').textContent='אפשר לבחור עד חמישה הרגלים. אפשר להסיר אחד כדי להוסיף הרגל אישי.';return;}const id='custom-'+Date.now();model.habits.push({id,title,hint:'הרגל אישי',target:title,time:'20:00',reminder:false});model.selected.push(id);save();render();}
 if(e.target.id==='rhythm-form'){const form=new FormData(e.target);for(const h of active()){h.target=String(form.get('target-'+h.id)).trim();h.time=String(form.get('time-'+h.id));h.reminder=form.has('reminder-'+h.id);}ensureStart();save();navigate('today');}
 if(e.target.id==='reflection-form'){updateRecord({note:$('#reflection-note').value.trim(),next:$('#reflection-next')?.value.trim()||'',closed:true});$('#reflection-status').textContent=demoDay?'הסיכום נשמר בהמחשה.':storageWorks?'הסיכום שמור במכשיר שלך.':'נשמר בעמוד הפתוח בלבד. השמירה במכשיר אינה זמינה.';}
});
document.addEventListener('input',e=>{if(e.target.id==='goal')e.target.setCustomValidity('');if(e.target.closest('#rhythm-form')){for(const h of active()){const box=screen.querySelector(`[data-reminder-preview="${h.id}"]`);box.hidden=!screen.querySelector(`[name="reminder-${h.id}"]`).checked;box.querySelector('[data-preview-time]').textContent=screen.querySelector(`[name="time-${h.id}"]`).value;box.querySelector('[data-preview-text]').textContent=reminderText({...h,target:screen.querySelector(`[name="target-${h.id}"]`).value});}}});
document.addEventListener('change',e=>{if(e.target.id==='keep-habit'){model.keepHabit=e.target.value;save();$('#keep-status').textContent=storageWorks?'הבחירה שמורה במכשיר הזה.':'הבחירה נשמרה בעמוד הפתוח בלבד.';}});
$('#demo-day').addEventListener('change',e=>{demoDay=Number(e.target.value);viewDay=null;navigate(demoDay===21?'summary':demoDay===7?'journey':'today');});
render();
