import * as en from "@/lib/content";
import * as he from "@/lib/content-he";
import type { Locale } from "@/lib/i18n";

export function getContent(locale: Locale) {
  const source = locale === "he" ? he : en;
  return {
    projects: source.projects,
    metrics: source.metrics,
    evidence: source.evidence,
    copy: copy[locale],
  };
}

// Server-rendered page text. Client component strings live in lib/i18n.ts.
export const copy = {
  en: {
    availability: "AVAILABLE FOR NEW OPPORTUNITIES",
    role: "AI DEPLOYMENT & GTM BUILDER",
    heroTitle: "I build and deploy AI systems that connect business workflows",
    heroAccent: "to revenue.",
    heroDescription:
      "Outbound platforms, voice agents, calling systems and CRM workflows: designed, built and deployed in production, with a clear link to commercial outcomes.",
    overviewTitle: "90-Second Overview",
    overviewCaption: "90 seconds of product demos, with English subtitles.",
    watchOverview: "Watch the 90-second overview",
    viewProjects: "View projects",
    portraitAlt: "Eyal Taieb, AI Deployment and GTM Builder",
    portraitLabel: "Business and technology.",
    portraitSubLabel: "Commercial experience and hands-on engineering.",
    downloadPortfolio: "Download one-page portfolio (PDF)",
    portraitCaption: "PORTFOLIO",
    metricsLabel: "Career commercial highlights",
    metricsNote:
      "Career commercial results. Supporting records are shown below.",
    projectsEyebrow: "01 / SELECTED WORK",
    projectsTitle: "Production systems,",
    projectsMuted: "built and deployed end to end.",
    projectsIntro:
      "Each system can be adapted to an organization’s existing workflows, data and infrastructure.",
    reelEyebrow: "PRODUCT OVERVIEW",
    reelTitle: "A 90-second",
    reelTitle2: "product overview",
    reelText:
      "AI outbound, voice agents, calling systems and connected revenue workflows.",
    reelDialogTitle: "90-Second Product Overview",
    reelCaption:
      "A 90-second edit of product demos, with English subtitles and commercial evidence.",
    watchReel: "Watch the overview",
    readTranscript: "Read the transcript",
    reelTopbar: "EYAL TAIEB / SELECTED WORK",
    reelSubtitles: "ENGLISH SUBTITLES",
    evidenceEyebrow: "02 / COMMERCIAL TRACK RECORD",
    evidenceTitle: "A commercial track record",
    evidenceMuted: "behind the systems.",
    evidenceIntro:
      "Customer conversations, technical sales and pipeline ownership inform how each system is designed.",
    evidenceContext:
      "Original photographs and dashboard screenshots. Select an image to view it in full.",
    aboutEyebrow: "03 / ABOUT",
    aboutTitle: "Between business",
    aboutMuted: "and technology.",
    aboutText:
      "I spent several years building B2B pipeline and selling technical products before focusing on building AI systems myself. As a result, I approach software from both sides: what needs to be built technically, and what is required for people to adopt it and create business value.",
    viewCv: "View CV (PDF)",
    tools: "TECHNOLOGIES",
    toolsNote:
      "Selected technologies. Project-specific details are described in each case study.",
    experience: "EXPERIENCE",
    projectFocus: "Project focus",
    mobileWorkflow: "MOBILE WORKFLOW",
    productWalkthrough: "PRODUCT WALKTHROUGH",
    recordingAlt: (name: string) => `${name}, product recording`,
    portraitNote: ["A clear next step", "after every call."],
    productFootage: "Product footage",
    watchDemo: "Watch demo",
    selectedWork: "SELECTED WORK",
    caseStudyLink: "View the case study",
    contactEyebrow: "CONTACT",
    contactTitle: "Available for",
    contactMuted: "new opportunities.",
    contactText:
      "Open to roles in AI Deployment, Forward Deployed AI, GTM Engineering, AI Solutions Engineering and AI Automation.",
    contactButton: "Contact by email",
    linkedin: "LinkedIn profile",
    footerRole: "AI Deployment & GTM Builder",
    viewCvShort: "View CV",
    owner: "Eyal Taieb",
  },
  he: {
    availability: "פתוח להזדמנויות חדשות",
    role: "AI DEPLOYMENT & GTM",
    heroTitle: "אני בונה ומטמיע מערכות AI שמחברות תהליכים עסקיים",
    heroAccent: "להכנסות.",
    heroDescription:
      "מערכות לפנייה יזומה, סוכנים קוליים, מערכות חיוג ותהליכי CRM: מתוכננים, נבנים ומוטמעים בסביבת ייצור, עם קשר ברור לתוצאות עסקיות.",
    overviewTitle: "סקירה בת 90 שניות",
    overviewCaption: "90 שניות של הדגמות מוצר, עם כתוביות באנגלית.",
    watchOverview: "צפייה בסקירה (90 שניות)",
    viewProjects: "לפרויקטים",
    portraitAlt: "אייל טייב, AI Deployment & GTM",
    portraitLabel: "עסקים וטכנולוגיה.",
    portraitSubLabel: "ניסיון מסחרי לצד פיתוח בפועל.",
    downloadPortfolio: "תיק עבודות בעמוד אחד, באנגלית (PDF)",
    portraitCaption: "תיק עבודות",
    metricsLabel: "הישגים מסחריים לאורך הקריירה",
    metricsNote: "תוצאות מסחריות לאורך הקריירה. התיעוד התומך מוצג בהמשך.",
    projectsEyebrow: "01 / פרויקטים נבחרים",
    projectsTitle: "מערכות בסביבת ייצור,",
    projectsMuted: "מהתכנון ועד ההטמעה.",
    projectsIntro:
      "ניתן להתאים כל מערכת לתהליכי העבודה, לנתונים ולתשתיות הקיימים בארגון.",
    reelEyebrow: "סקירת מוצרים",
    reelTitle: "סקירת מוצרים",
    reelTitle2: "ב־90 שניות",
    reelText:
      "פנייה יזומה מבוססת AI, סוכנים קוליים, מערכות חיוג ותהליכי הכנסות מחוברים.",
    reelDialogTitle: "סקירת מוצרים ב־90 שניות",
    reelCaption:
      "עריכה של 90 שניות מתוך הדגמות המוצר, עם כתוביות באנגלית ותיעוד מסחרי.",
    watchReel: "צפייה בסקירה",
    readTranscript: "תמליל (באנגלית)",
    reelTopbar: "EYAL TAIEB / SELECTED WORK",
    reelSubtitles: "כתוביות באנגלית",
    evidenceEyebrow: "02 / רקע מסחרי",
    evidenceTitle: "ניסיון מסחרי מוכח",
    evidenceMuted: "שעומד מאחורי המערכות.",
    evidenceIntro:
      "שיחות עם לקוחות, מכירה טכנית ואחריות על Pipeline הם הבסיס לאופן שבו כל מערכת מתוכננת.",
    evidenceContext:
      "צילומים מקוריים וצילומי מסך של לוחות בקרה. ניתן לבחור תמונה כדי להציג אותה במלואה.",
    aboutEyebrow: "03 / אודות",
    aboutTitle: "בין עסקים",
    aboutMuted: "לטכנולוגיה.",
    aboutText:
      "במשך כמה שנים בניתי Pipeline בתחום ה־B2B ומכרתי מוצרים טכניים, לפני שהתמקדתי בבניית מערכות AI בעצמי. כתוצאה מכך אני ניגש לתוכנה משני הצדדים: מה צריך להיבנות מבחינה טכנית, ומה נדרש כדי שאנשים יאמצו אותה והיא תייצר ערך עסקי.",
    viewCv: "קורות חיים באנגלית (PDF)",
    tools: "טכנולוגיות",
    toolsNote:
      "טכנולוגיות נבחרות. הפרטים של כל פרויקט מופיעים בתיאור המקרה שלו.",
    experience: "ניסיון",
    projectFocus: "תחומי הפרויקט",
    mobileWorkflow: "תהליך בנייד",
    productWalkthrough: "הדגמת מוצר",
    recordingAlt: (name: string) => `${name}, הקלטת מוצר`,
    portraitNote: ["צעד הבא ברור", "אחרי כל שיחה."],
    productFootage: "צילומי מוצר",
    watchDemo: "צפייה בהדגמה",
    selectedWork: "פרויקטים נבחרים",
    caseStudyLink: "לתיאור הפרויקט",
    contactEyebrow: "יצירת קשר",
    contactTitle: "פתוח",
    contactMuted: "להזדמנויות חדשות.",
    contactText:
      "פתוח לתפקידי AI Deployment, Forward Deployed AI, GTM Engineering, AI Solutions Engineering ו־AI Automation.",
    contactButton: "פנייה בדוא״ל",
    linkedin: "פרופיל LinkedIn",
    footerRole: "AI Deployment & GTM",
    viewCvShort: "קורות חיים",
    owner: "אייל טייב",
  },
};

export const caseCopy = {
  en: {
    allProjects: "All projects",
    projectFocus: "Project focus",
    readTranscript: "Read the transcript",
    selectedWork: "SELECTED WORK",
    watchFullDemo: "Watch the full demo",
    sectionsLabel: "Case study sections",
    problem: "Problem",
    built: "What I Built",
    workflow: "How It Works",
    architecture: "Architecture",
    demo: "Demo",
    value: "Business Value",
    learned: "Key Takeaway",
    problemEyebrow: "01 / THE STARTING POINT",
    builtEyebrow: "02 / THE IMPLEMENTATION",
    workflowEyebrow: "03 / THE CONNECTED WORKFLOW",
    architectureEyebrow: "04 / UNDER THE HOOD",
    architectureTitle: "Technical Architecture",
    componentsLabel: "CORE COMPONENTS",
    demoEyebrow: "05 / DEMO",
    fullRecording: (duration: string) =>
      `Full recording · ${duration} · English subtitles`,
    mobileDemo: "Mobile calling workflow",
    desktopDemo: "Product walkthrough",
    previewAlt: (name: string) => `Preview of the ${name} demo`,
    soundOn: "Sound on",
    downloadSubtitles: "Download subtitles",
    valueEyebrow: "06 / BUSINESS CONTEXT",
    learnedEyebrow: "07 / DESIGN PRINCIPLE",
    nextProject: "NEXT PROJECT",
  },
  he: {
    allProjects: "כל הפרויקטים",
    projectFocus: "תחומי הפרויקט",
    readTranscript: "תמליל (באנגלית)",
    selectedWork: "פרויקטים נבחרים",
    watchFullDemo: "צפייה בהדגמה המלאה",
    sectionsLabel: "חלקי תיאור הפרויקט",
    problem: "האתגר",
    built: "מה בניתי",
    workflow: "איך זה עובד",
    architecture: "ארכיטקטורה",
    demo: "הדגמה",
    value: "ערך עסקי",
    learned: "תובנה מרכזית",
    problemEyebrow: "01 / נקודת המוצא",
    builtEyebrow: "02 / המימוש",
    workflowEyebrow: "03 / התהליך המחובר",
    architectureEyebrow: "04 / מאחורי הקלעים",
    architectureTitle: "ארכיטקטורה טכנית",
    componentsLabel: "רכיבים מרכזיים",
    demoEyebrow: "05 / הדגמה",
    fullRecording: (duration: string) =>
      `הקלטה מלאה · ${duration} · כתוביות באנגלית`,
    mobileDemo: "תהליך חיוג בנייד",
    desktopDemo: "הדגמת מוצר",
    previewAlt: (name: string) => `תצוגה מקדימה של ההדגמה של ${name}`,
    soundOn: "עם קול",
    downloadSubtitles: "הורדת כתוביות (באנגלית)",
    valueEyebrow: "06 / ההקשר העסקי",
    learnedEyebrow: "07 / עיקרון תכנוני",
    nextProject: "הפרויקט הבא",
  },
};
